/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis;

import java.awt.Color;

import sisescola_java.paginasis.Turmas.TelaTurmas;
import sisescola_java.paginasis.Aluno.TelaAluno;
import sisescola_java.paginasis.Horarios.TelaHorarios;
import sisescola_java.paginasis.Professores.TelaProfessores;
import sisescola_java.paginasis.Materias.TelaMaterias;
import sisescola_java.paginasis.Responsavel.TelaResponsavel;

/**
 *
 * @author Matheus
 */
public class TelaCRUDS extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCRUDS() {
        initComponents();
    }

    TelaCRUDS(String nome, String Senha) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        pnlPrincipalC = new javax.swing.JPanel();
        lblAluno = new javax.swing.JLabel();
        lblProfessor = new javax.swing.JLabel();
        btProfessor = new javax.swing.JButton();
        btAluno = new javax.swing.JButton();
        btTurmas = new javax.swing.JButton();
        lblTurma = new javax.swing.JLabel();
        lblMaterias = new javax.swing.JLabel();
        btMaterias = new javax.swing.JButton();
        btResp = new javax.swing.JButton();
        lblResp = new javax.swing.JLabel();
        btDeslogar = new javax.swing.JButton();
        btResp1 = new javax.swing.JButton();
        lblTurma1 = new javax.swing.JLabel();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");
        setBackground(new java.awt.Color(204, 204, 204));
        setName("telaCdst"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Opções");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        lblAluno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAluno.setForeground(new java.awt.Color(2, 48, 71));
        lblAluno.setText("Aluno");

        lblProfessor.setBackground(new java.awt.Color(204, 204, 204));
        lblProfessor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblProfessor.setForeground(new java.awt.Color(2, 48, 71));
        lblProfessor.setText("Professor");

        btProfessor.setBackground(new java.awt.Color(142, 202, 230));
        btProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeProfessor.png"))); // NOI18N
        btProfessor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProfessorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProfessorMouseExited(evt);
            }
        });
        btProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfessorActionPerformed(evt);
            }
        });

        btAluno.setBackground(new java.awt.Color(142, 202, 230));
        btAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeAluno.png"))); // NOI18N
        btAluno.setToolTipText("");
        btAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAlunoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlunoMouseExited(evt);
            }
        });
        btAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlunoActionPerformed(evt);
            }
        });

        btTurmas.setBackground(new java.awt.Color(142, 202, 230));
        btTurmas.setForeground(new java.awt.Color(142, 202, 230));
        btTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeTurma2.png"))); // NOI18N
        btTurmas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btTurmasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btTurmasMouseExited(evt);
            }
        });
        btTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTurmasActionPerformed(evt);
            }
        });

        lblTurma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTurma.setForeground(new java.awt.Color(2, 48, 71));
        lblTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurma.setText("Turmas");

        lblMaterias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMaterias.setForeground(new java.awt.Color(2, 48, 71));
        lblMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaterias.setText("Matérias");

        btMaterias.setBackground(new java.awt.Color(142, 202, 230));
        btMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeMaterias.png"))); // NOI18N
        btMaterias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMateriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMateriasMouseExited(evt);
            }
        });
        btMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMateriasActionPerformed(evt);
            }
        });

        btResp.setBackground(new java.awt.Color(142, 202, 230));
        btResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeFamilia.png"))); // NOI18N
        btResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btResp.setMaximumSize(new java.awt.Dimension(144, 144));
        btResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRespMouseExited(evt);
            }
        });
        btResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRespActionPerformed(evt);
            }
        });

        lblResp.setBackground(new java.awt.Color(0, 0, 0));
        lblResp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblResp.setForeground(new java.awt.Color(2, 48, 71));
        lblResp.setText("Responsáveis");

        btDeslogar.setBackground(new java.awt.Color(142, 202, 230));
        btDeslogar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDeslogar.setForeground(new java.awt.Color(2, 48, 71));
        btDeslogar.setText("Logoff");
        btDeslogar.setBorder(null);
        btDeslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeslogarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDeslogarMouseExited(evt);
            }
        });
        btDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeslogarActionPerformed(evt);
            }
        });

        btResp1.setBackground(new java.awt.Color(142, 202, 230));
        btResp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Escala.png"))); // NOI18N
        btResp1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btResp1.setMaximumSize(new java.awt.Dimension(144, 144));
        btResp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btResp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btResp1MouseExited(evt);
            }
        });
        btResp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResp1ActionPerformed(evt);
            }
        });

        lblTurma1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTurma1.setForeground(new java.awt.Color(2, 48, 71));
        lblTurma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurma1.setText("Horários");

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTurma))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblAluno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(btDeslogar)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btResp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(lblTurma1)
                        .addGap(101, 101, 101)))
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(lblProfessor))
                        .addComponent(btMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblMaterias)))
                .addGap(138, 138, 138))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(lblAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(lblResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btResp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(lblProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaterias)
                            .addComponent(lblTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btResp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btDeslogar)
                        .addContainerGap())))
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addGap(343, 343, 343))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTurmasActionPerformed
        TelaTurmas Tt = new TelaTurmas();
        Tt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btTurmasActionPerformed

    private void btAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlunoActionPerformed
        TelaAluno Ta = new TelaAluno();
        Ta.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAlunoActionPerformed

    private void btProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfessorActionPerformed
        TelaProfessores Tp = new TelaProfessores();
        Tp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btProfessorActionPerformed

    private void btMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMateriasActionPerformed
        TelaMaterias Tm = new TelaMaterias();
        Tm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btMateriasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRespActionPerformed
        TelaResponsavel TR = new TelaResponsavel();
        TR.setVisible(true);
        dispose();
    }//GEN-LAST:event_btRespActionPerformed

    private void btDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeslogarActionPerformed
        Telalogin Tl = new Telalogin();
        Tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btDeslogarActionPerformed

    private void btMateriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMateriasMouseEntered
        btMaterias.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btMateriasMouseEntered

    private void btMateriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMateriasMouseExited
        btMaterias.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btMateriasMouseExited

    private void btProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProfessorMouseEntered
        btProfessor.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btProfessorMouseEntered

    private void btProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProfessorMouseExited
        btProfessor.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btProfessorMouseExited

    private void btAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlunoMouseEntered
        btAluno.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btAlunoMouseEntered

    private void btAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlunoMouseExited
        btAluno.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btAlunoMouseExited

    private void btRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRespMouseEntered
        btResp.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btRespMouseEntered

    private void btRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRespMouseExited
        btResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btRespMouseExited

    private void btTurmasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTurmasMouseEntered
        btTurmas.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btTurmasMouseEntered

    private void btTurmasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTurmasMouseExited
        btTurmas.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btTurmasMouseExited

    private void btDeslogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeslogarMouseEntered
        btDeslogar.setForeground(new Color(251,133,0));
    }//GEN-LAST:event_btDeslogarMouseEntered

    private void btDeslogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeslogarMouseExited
        btDeslogar.setForeground(new Color(2,48,71));
    }//GEN-LAST:event_btDeslogarMouseExited

    private void btResp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResp1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btResp1MouseEntered

    private void btResp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResp1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btResp1MouseExited

    private void btResp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResp1ActionPerformed
        TelaHorarios th = new TelaHorarios();
        th.setVisible(true);
        dispose();
    }//GEN-LAST:event_btResp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUDS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAluno;
    private javax.swing.JButton btDeslogar;
    private javax.swing.JButton btMaterias;
    private javax.swing.JButton btProfessor;
    private javax.swing.JButton btResp;
    private javax.swing.JButton btResp1;
    private javax.swing.JButton btTurmas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JLabel lblResp;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JLabel lblTurma1;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    // End of variables declaration//GEN-END:variables
}
