/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import sisescola_java.Objetos1.ConnectionFactory;
import sisescola_java.paginasis.Telalogin;
import sisescola_java.paginasis.Aluno.TelaAluno;
import sisescola_java.paginasis.Telalogin;
/**
 *
 * @author Matheus
 */
public class TelaEsqSenha extends javax.swing.JFrame {
    private void buscarAdministrador() {
        String cpf = txtCPF.getText().trim();
        if (cpf.isEmpty()) {
            lblStatus.setText("CPF não pode ser vazio.");
            return;
        }
        
        // Conectar ao banco e verificar se o CPF existe
        try (Connection con = ConnectionFactory.getConnection();
             PreparedStatement stmt = con.prepareStatement("SELECT * FROM Administradores WHERE CPF = ?")) {
            stmt.setString(1, cpf);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                lblStatus.setText("Administrador encontrado.");
            } else {
                lblStatus.setText("Administrador não encontrado.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            lblStatus.setText("Erro na busca: " + ex.getMessage());
        }
    }

    private void alterarSenhaAdministrador() {
        String cpf = txtCPF.getText().trim();
        String novaSenha = new String(txtNovaSenha.getText()).trim();
        String repetirSenha = new String(txtRNovaSenha.getText()).trim();
        if(novaSenha != repetirSenha){
            lblStatus.setText("");
            lblStatus.setText("As senhas precisam ser iguais nos 2 campos.");
        }
        if (cpf.isBlank() || novaSenha.isBlank()) {
            lblStatus.setText("");
            lblStatus.setText("CPF e Senha não podem ser vazios.");
            return;
        }

        // Conectar ao banco e atualizar a senha
        try (Connection con = ConnectionFactory.getConnection();
             PreparedStatement stmt = con.prepareStatement("UPDATE Administradores SET Senha = ? WHERE CPF = ?")) {
            stmt.setString(1, novaSenha);
            stmt.setString(2, cpf);
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                lblStatus.setText("Senha alterada com sucesso.");
            } else {
                lblStatus.setText("Erro ao alterar a senha.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            lblStatus.setText("Erro na alteração: " + ex.getMessage());
        }
    }
    /**
     * Creates new form TelaEsqSenha
     */
    public TelaEsqSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLoginTop = new javax.swing.JLabel();
        lbLoginTop2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLoginTop1 = new javax.swing.JLabel();
        lbLoginTop3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRNovaSenha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        btnVoltarEsqA = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));

        lblLoginTop.setBackground(new java.awt.Color(251, 133, 0));
        lblLoginTop.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLoginTop.setForeground(new java.awt.Color(251, 133, 0));
        lblLoginTop.setText("SYST");

        lbLoginTop2.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        lbLoginTop2.setForeground(new java.awt.Color(142, 202, 230));
        lbLoginTop2.setText("edu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lbLoginTop2)
                .addGap(0, 0, 0)
                .addComponent(lblLoginTop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginTop)
                    .addComponent(lbLoginTop2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(2, 48, 71));

        lblLoginTop1.setBackground(new java.awt.Color(251, 133, 0));
        lblLoginTop1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLoginTop1.setForeground(new java.awt.Color(251, 133, 0));
        lblLoginTop1.setText("SYST");

        lbLoginTop3.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        lbLoginTop3.setForeground(new java.awt.Color(142, 202, 230));
        lbLoginTop3.setText("edu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lbLoginTop3)
                .addGap(0, 0, 0)
                .addComponent(lblLoginTop1)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginTop1)
                    .addComponent(lbLoginTop3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(142, 202, 230));

        lblStatus.setBackground(new java.awt.Color(142, 202, 230));
        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(2, 48, 71));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Status:");

        txtNovaSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNovaSenha.setForeground(new java.awt.Color(2, 48, 71));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("Repita a Senha:");

        txtRNovaSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtRNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRNovaSenha.setForeground(new java.awt.Color(2, 48, 71));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(2, 48, 71));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSenha.setBackground(new java.awt.Color(142, 202, 230));
        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(2, 48, 71));
        lblSenha.setText("Nova Senha:");

        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(2, 48, 71));
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        lblCPF.setBackground(new java.awt.Color(142, 202, 230));
        lblCPF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(2, 48, 71));
        lblCPF.setText("CPF:");

        btnVoltarEsqA.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarEsqA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarEsqA.setToolTipText("Voltar");
        btnVoltarEsqA.setBorder(null);
        btnVoltarEsqA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarEsqAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarEsqAMouseExited(evt);
            }
        });
        btnVoltarEsqA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarEsqAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltarEsqA)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCPF)
                            .addComponent(lblSenha)
                            .addComponent(jLabel2)
                            .addComponent(txtNovaSenha)
                            .addComponent(txtRNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCPF))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnVoltarEsqA)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        alterarSenhaAdministrador();
        txtNovaSenha.setText("");
        txtRNovaSenha.setText("");
        txtCPF.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnVoltarEsqAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarEsqAMouseEntered
        btnVoltarEsqA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarEsqAMouseEntered

    private void btnVoltarEsqAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarEsqAMouseExited
        btnVoltarEsqA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarEsqAMouseExited

    private void btnVoltarEsqAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarEsqAActionPerformed
        Telalogin tl = new Telalogin();
        tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarEsqAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEsqSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEsqSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEsqSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEsqSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEsqSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarEsqA;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbLoginTop2;
    private javax.swing.JLabel lbLoginTop3;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblLoginTop;
    private javax.swing.JLabel lblLoginTop1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblStatus;
    public javax.swing.JTextField txtCPF;
    public javax.swing.JTextField txtNovaSenha;
    private javax.swing.JTextField txtRNovaSenha;
    // End of variables declaration//GEN-END:variables
}
