/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Aluno;

import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import sisescola_java.Objetos1.Aluno;
import sisescola_java.Objetos1.AlunoDAO;

/**
 *
 * @author Matheus
 */
public class TelaDelAluno extends javax.swing.JFrame {

    public void btconsulta(String pesquisa) {
        AlunoDAO adao = new AlunoDAO();
        try {
            // Verifica se a string de pesquisa é um CPF (números com 11 dígitos)
            if (pesquisa.matches("\\d{11}")) {
                // Consulta pelo CPF
                for (Aluno a : adao.btconsultar(null, pesquisa)) {

                    lblIDA.setText(String.valueOf(a.getId_Aluno()));
                    lblCPFA.setText(a.getCPFAluno());
                    lblNomeA.setText(a.getNomeA());
                    lblEmailA.setText(a.getEmailA());
                    lblNascA.setText(a.getData_NascA());
                    lblEnderecoA.setText(a.getEnderecoA());
                    lblTelefoneA.setText(a.getTelefoneA());
                    lblGeneroA.setText(a.getGeneroA());
                    lblResponsavelA.setText(a.getNomeResponsavel());
                }
            } else {
                // Consulta pelo Nome
                for (Aluno a : adao.btconsultar(pesquisa, null)) {

                    lblIDA.setText(String.valueOf(a.getId_Aluno()));
                    lblCPFA.setText(a.getCPFAluno());
                    lblNomeA.setText(a.getNomeA());
                    lblEmailA.setText(a.getEmailA());
                    lblNascA.setText(a.getData_NascA());
                    lblEnderecoA.setText(a.getEnderecoA());
                    lblTelefoneA.setText(a.getTelefoneA());
                    lblGeneroA.setText(a.getGeneroA());
                    lblResponsavelA.setText(a.getNomeResponsavel());
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaConsAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*
    Vector<Integer> Id_Responsavel = new Vector<Integer>();
    Vector<Integer> Id_Turma = new Vector<Integer>();

    public void boxReps() {

        try {
            AlunoDAO ald = new AlunoDAO();
            ResultSet rs = ald.listarResponsaveis();

            while (rs.next()) {
                Id_Responsavel.addElement(rs.getInt(1));
                boxRespA.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na combobox do responsável " + e);
        }
    }

    public void boxTurmas() {

        try {
            AlunoDAO ald = new AlunoDAO();
            ResultSet rs = ald.listarTurmas();

            while (rs.next()) {
                Id_Turma.addElement(rs.getInt(1));
                boxTurmaA.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na combobox do responsável " + e);
        }
    }

    /**
     * Creates new form TelaDelAluno
     */
    public TelaDelAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        pnlPrincipalC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnVoltarExcA = new javax.swing.JButton();
        btDeletarA = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btLimparA = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblIDA = new javax.swing.JLabel();
        lblNomeA = new javax.swing.JLabel();
        lblEmailA = new javax.swing.JLabel();
        lblNascA = new javax.swing.JLabel();
        lblEnderecoA = new javax.swing.JLabel();
        lblTelefoneA = new javax.swing.JLabel();
        lblGeneroA = new javax.swing.JLabel();
        lblResponsavelA = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCPFA = new javax.swing.JLabel();
        txtNomeAlunoP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btpesquisade = new javax.swing.JButton();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deletar Aluno");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Excluir");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setText("Endereço:");

        jLabel5.setBackground(new java.awt.Color(2, 48, 71));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setText("Nascimento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 48, 71));
        jLabel8.setText("Responsável:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 48, 71));
        jLabel9.setText("Telefone:");

        btnVoltarExcA.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarExcA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarExcA.setToolTipText("Voltar");
        btnVoltarExcA.setBorder(null);
        btnVoltarExcA.setName(""); // NOI18N
        btnVoltarExcA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarExcAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarExcAMouseExited(evt);
            }
        });
        btnVoltarExcA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarExcAActionPerformed(evt);
            }
        });

        btDeletarA.setBackground(new java.awt.Color(142, 202, 230));
        btDeletarA.setForeground(new java.awt.Color(2, 48, 71));
        btDeletarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        btDeletarA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 5, true));
        btDeletarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeletarAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDeletarAMouseExited(evt);
            }
        });
        btDeletarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarAActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 48, 71));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("EXCLUIR ALUNO");

        btLimparA.setBackground(new java.awt.Color(142, 202, 230));
        btLimparA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar.png"))); // NOI18N
        btLimparA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btLimparA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparAMouseExited(evt);
            }
        });
        btLimparA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparAActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 48, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIMPAR");

        lblIDA.setBackground(new java.awt.Color(2, 48, 71));
        lblIDA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDA.setForeground(new java.awt.Color(2, 48, 71));
        lblIDA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIDA.setText("ID");
        lblIDA.setToolTipText("");
        lblIDA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIDA.setPreferredSize(new java.awt.Dimension(18, 16));
        lblIDA.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblIDAInputMethodTextChanged(evt);
            }
        });

        lblNomeA.setBackground(new java.awt.Color(2, 48, 71));
        lblNomeA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeA.setForeground(new java.awt.Color(2, 48, 71));
        lblNomeA.setText("Nome");

        lblEmailA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailA.setForeground(new java.awt.Color(2, 48, 71));
        lblEmailA.setText("Email");

        lblNascA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNascA.setForeground(new java.awt.Color(2, 48, 71));
        lblNascA.setText("Data de Nascimento");

        lblEnderecoA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnderecoA.setForeground(new java.awt.Color(2, 48, 71));
        lblEnderecoA.setText("Endereço");

        lblTelefoneA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefoneA.setForeground(new java.awt.Color(2, 48, 71));
        lblTelefoneA.setText("Telefone");

        lblGeneroA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGeneroA.setForeground(new java.awt.Color(2, 48, 71));
        lblGeneroA.setText("Gênero");

        lblResponsavelA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResponsavelA.setForeground(new java.awt.Color(2, 48, 71));
        lblResponsavelA.setText("Nome Responsável");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 48, 71));
        jLabel15.setText("CPF:");

        lblCPFA.setBackground(new java.awt.Color(2, 48, 71));
        lblCPFA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPFA.setForeground(new java.awt.Color(2, 48, 71));
        lblCPFA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPFA.setText("CPF");
        lblCPFA.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblCPFAInputMethodTextChanged(evt);
            }
        });

        txtNomeAlunoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoPActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 48, 71));
        jLabel10.setText("Nome ou CPF do aluno:");

        btpesquisade.setText("Pesquisar");
        btpesquisade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarExcA)
                .addGap(45, 45, 45)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNomeA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEmailA, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblCPFA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNascA))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblEnderecoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblGeneroA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTelefoneA, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblResponsavelA)))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDeletarA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLimparA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAlunoP, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btpesquisade)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnVoltarExcA)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNomeAlunoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btpesquisade))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDeletarA, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimparA, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblIDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblCPFA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblNomeA))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblEmailA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblNascA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblEnderecoA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lblTelefoneA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblGeneroA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lblResponsavelA))))))
                .addContainerGap())
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarExcAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarExcAMouseEntered
        btnVoltarExcA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarExcAMouseEntered

    private void btnVoltarExcAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarExcAMouseExited
        btnVoltarExcA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarExcAMouseExited

    private void btnVoltarExcAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarExcAActionPerformed
        TelaAluno a = new TelaAluno();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarExcAActionPerformed

    private void btDeletarAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarAMouseEntered
        btDeletarA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btDeletarAMouseEntered

    private void btDeletarAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarAMouseExited
        btDeletarA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btDeletarAMouseExited

    private void btDeletarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarAActionPerformed
        AlunoDAO A = new AlunoDAO();
        String nome = lblNomeA.getText();
        String cpf = lblCPFA.getText();

        if ((nome.isEmpty() || nome.equals("Nome")) && (cpf.isEmpty() || cpf.equals("CPF"))) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um nome ou CPF para exclusão.");
            return;
        }
        try {
            int i = JOptionPane.showConfirmDialog(null, "Deseja excluir este aluno? Essa ação é irreversível");
            if (i == JOptionPane.YES_OPTION) {
                A.Excluir(nome, cpf);
                A.btconsultar("", ""); // Atualiza a tabela após a exclusão
                lblIDA.setText("");
                lblCPFA.setText("");
                lblNomeA.setText("");
                lblEmailA.setText("");
                lblNascA.setText("");
                lblEnderecoA.setText("");
                lblTelefoneA.setText("");
                lblGeneroA.setText("");
                lblResponsavelA.setText("");
                txtNomeAlunoP.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaConsAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDeletarAActionPerformed

    private void btLimparAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparAActionPerformed
        lblIDA.setText("");
        lblCPFA.setText("");
        lblNomeA.setText("");
        lblEmailA.setText("");
        lblNascA.setText("");
        lblEnderecoA.setText("");
        lblTelefoneA.setText("");
        lblGeneroA.setText("");
        lblResponsavelA.setText("");
        txtNomeAlunoP.setText("");
    }//GEN-LAST:event_btLimparAActionPerformed

    private void btLimparAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparAMouseExited
        btLimparA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btLimparAMouseExited

    private void btLimparAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparAMouseEntered
        btLimparA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btLimparAMouseEntered

    private void lblIDAInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblIDAInputMethodTextChanged

    }//GEN-LAST:event_lblIDAInputMethodTextChanged

    private void lblCPFAInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblCPFAInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCPFAInputMethodTextChanged

    private void btpesquisadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisadeActionPerformed
        btconsulta(txtNomeAlunoP.getText());
    }//GEN-LAST:event_btpesquisadeActionPerformed

    private void txtNomeAlunoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDelAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDelAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDelAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDelAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDelAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeletarA;
    private javax.swing.JButton btLimparA;
    private javax.swing.JButton btnVoltarExcA;
    private javax.swing.JButton btpesquisade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblCPFA;
    private javax.swing.JLabel lblEmailA;
    private javax.swing.JLabel lblEnderecoA;
    private javax.swing.JLabel lblGeneroA;
    private javax.swing.JLabel lblIDA;
    private javax.swing.JLabel lblNascA;
    private javax.swing.JLabel lblNomeA;
    private javax.swing.JLabel lblResponsavelA;
    private javax.swing.JLabel lblTelefoneA;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTextField txtNomeAlunoP;
    // End of variables declaration//GEN-END:variables
}
