/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Aluno;

import sisescola_java.paginasis.Turmas.TelaEnturmar;
import sisescola_java.Objetos1.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaCadAluno extends javax.swing.JFrame {

    Vector<Integer> Id_Responsavel = new Vector<Integer>();

    private int getIdFromComboBox(JComboBox<String> comboBox, Vector<Integer> idList) {
        int index = comboBox.getSelectedIndex();
        if (index >= 0 && index < idList.size()) {
            return idList.get(index);
        }
        return -1; // Retorna -1 se não encontrar um ID válido
    }

    public boolean alunoExists(String cpf) throws SQLException, ClassNotFoundException {
        String query = "SELECT COUNT(*) FROM Alunos WHERE CPF = ?";
        try (Connection con = ConnectionFactory.getConnection(); PreparedStatement stmt = con.prepareStatement(query)) {
            stmt.setString(1, cpf);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1) > 0;
                }
            }
        }
        return false;
    }

    public void boxReps() {
        try {
            AlunoDAO ald = new AlunoDAO();
            ResultSet rs = ald.listarResponsaveis();

            if (rs == null) {
                JOptionPane.showMessageDialog(null, "Erro ao obter dados dos responsáveis.");
                return;
            }

            Id_Responsavel.clear(); // Limpa a lista existente
            boxRespA.removeAllItems(); // Limpa a combobox

            while (rs.next()) {
                int idResponsavel = rs.getInt("Id_Responsavel");
                String nomeResponsavel = rs.getString("Nome");
                Id_Responsavel.addElement(idResponsavel);
                boxRespA.addItem(nomeResponsavel);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na combobox do responsável: " + e);
        }
    }

    public void selecionarResponsavel(int idResponsavel) {
        for (int i = 0; i < Id_Responsavel.size(); i++) {
            if (Id_Responsavel.get(i) == idResponsavel) {
                boxRespA.setSelectedIndex(i);
                return;
            }
        }
        // Se não encontrar o ID, desmarcar a seleção
        boxRespA.setSelectedIndex(-1);
    }

    public void boxGeneros() {
        try {
            AlunoDAO ald = new AlunoDAO();
            ResultSet rs = ald.listarGeneros();

            while (rs.next()) {
                String genero = rs.getString("Genero");
                // Verifica se o gênero já está na JComboBox
                boolean existe = false;
                for (int i = 0; i < boxGeneroA.getItemCount(); i++) {
                    if (boxGeneroA.getItemAt(i).equals(genero)) {
                        existe = true;
                        break;
                    }
                }
                if (!existe) {
                    boxGeneroA.addItem(genero);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na combobox do gênero: " + e);
        }
    }

    public void selecionarGenero(String genero) {
        for (int i = 0; i < boxGeneroA.getItemCount(); i++) {
            if (boxGeneroA.getItemAt(i).equals(genero)) {
                boxGeneroA.setSelectedIndex(i);
                return;
            }
        }
        // Se não encontrar o gênero, desmarcar a seleção
        boxGeneroA.setSelectedIndex(-1);
    }

    /**
     * Creates new form TelaCadALuno
     */
    public TelaCadAluno() {
        initComponents();
        boxReps();
        boxGeneros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        pnlPrincipalC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCPFA = new javax.swing.JTextField();
        txtEmailA = new javax.swing.JTextField();
        txtNomeA = new javax.swing.JTextField();
        txtDiaA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMesA = new javax.swing.JTextField();
        txtAnoA = new javax.swing.JTextField();
        txtEnderecoA = new javax.swing.JTextField();
        txtTelefoneA = new javax.swing.JTextField();
        boxGeneroA = new javax.swing.JComboBox<>();
        boxRespA = new javax.swing.JComboBox<>();
        btnVoltarCadA = new javax.swing.JButton();
        btInserirA = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btLimparA = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSenhaA = new javax.swing.JTextField();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Aluno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Cadastrar");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("CPF:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setText("Endereço:");

        jLabel5.setBackground(new java.awt.Color(2, 48, 71));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setText("Nascimento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 48, 71));
        jLabel8.setText("Responsável:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 48, 71));
        jLabel9.setText("Telefone:");

        txtCPFA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCPFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFAActionPerformed(evt);
            }
        });

        txtNomeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAActionPerformed(evt);
            }
        });

        txtDiaA.setForeground(new java.awt.Color(2, 48, 71));
        txtDiaA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 48, 71));
        jLabel10.setText("/");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(2, 48, 71));
        jLabel11.setText("/");

        txtMesA.setForeground(new java.awt.Color(2, 48, 71));
        txtMesA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesAActionPerformed(evt);
            }
        });

        txtAnoA.setForeground(new java.awt.Color(2, 48, 71));
        txtAnoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAnoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoAActionPerformed(evt);
            }
        });

        boxGeneroA.setForeground(new java.awt.Color(2, 48, 71));
        boxGeneroA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Homem Trans", "Mulher Trans", "Não Binário", "Outro" }));
        boxGeneroA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boxGeneroA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxGeneroAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boxGeneroAMouseExited(evt);
            }
        });
        boxGeneroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroAActionPerformed(evt);
            }
        });

        boxRespA.setForeground(new java.awt.Color(2, 48, 71));
        boxRespA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione" }));
        boxRespA.setToolTipText("Selecione");
        boxRespA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boxRespA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxRespAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boxRespAMouseExited(evt);
            }
        });
        boxRespA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRespAActionPerformed(evt);
            }
        });

        btnVoltarCadA.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarCadA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarCadA.setToolTipText("Voltar");
        btnVoltarCadA.setBorder(null);
        btnVoltarCadA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarCadAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarCadAMouseExited(evt);
            }
        });
        btnVoltarCadA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadAActionPerformed(evt);
            }
        });

        btInserirA.setBackground(new java.awt.Color(142, 202, 230));
        btInserirA.setForeground(new java.awt.Color(2, 48, 71));
        btInserirA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastar.png"))); // NOI18N
        btInserirA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 5, true));
        btInserirA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btInserirAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btInserirAMouseExited(evt);
            }
        });
        btInserirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirAActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 48, 71));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CADASTRAR ALUNO");

        btLimparA.setBackground(new java.awt.Color(142, 202, 230));
        btLimparA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar.png"))); // NOI18N
        btLimparA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btLimparA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparAMouseExited(evt);
            }
        });
        btLimparA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparAActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 48, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIMPAR");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 48, 71));
        jLabel14.setText("Senha:");

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarCadA)
                .addGap(49, 49, 49)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiaA, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMesA, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnoA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmailA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtCPFA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeA, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txtSenhaA, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxRespA, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnderecoA))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxGeneroA, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefoneA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimparA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btInserirA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(185, 185, 185))))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtCPFA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmailA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtSenhaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(txtMesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEnderecoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTelefoneA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxGeneroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(boxRespA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnVoltarCadA)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInserirA, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparA, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAActionPerformed

    private void txtAnoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoAActionPerformed

    private void txtNomeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAActionPerformed

    private void btInserirAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirAMouseEntered
        btInserirA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btInserirAMouseEntered

    private void btInserirAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirAMouseExited
        btInserirA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btInserirAMouseExited

    private void btnVoltarCadAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadAActionPerformed
        TelaAluno a = new TelaAluno();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarCadAActionPerformed

    private void btLimparAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparAActionPerformed
        txtCPFA.setText("");
        txtNomeA.setText("");
        txtEmailA.setText("");
        txtSenhaA.setText("");
        txtDiaA.setText("");
        txtMesA.setText("");
        txtAnoA.setText("");
        txtEnderecoA.setText("");
        txtTelefoneA.setText("");
        boxGeneroA.setSelectedIndex(0);
        boxRespA.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparAActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void boxGeneroAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroAMouseEntered

    }//GEN-LAST:event_boxGeneroAMouseEntered

    private void boxGeneroAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroAMouseExited

    }//GEN-LAST:event_boxGeneroAMouseExited

    private void btLimparAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparAMouseEntered
        btLimparA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btLimparAMouseEntered

    private void btLimparAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparAMouseExited
        btLimparA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btLimparAMouseExited

    private void boxRespAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxRespAMouseEntered

    }//GEN-LAST:event_boxRespAMouseEntered

    private void boxRespAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxRespAMouseExited

    }//GEN-LAST:event_boxRespAMouseExited

    private void btnVoltarCadAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadAMouseEntered
        btnVoltarCadA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarCadAMouseEntered

    private void btnVoltarCadAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadAMouseExited
        btnVoltarCadA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarCadAMouseExited

    private void btInserirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirAActionPerformed
        Aluno a = new Aluno();
        AlunoDAO dao = new AlunoDAO();
        if (txtCPFA.getText().equals("")
                || txtNomeA.getText().equals("")
                || txtEmailA.getText().equals("")
                || txtSenhaA.getText().equals("")
                || txtDiaA.getText().equals("")
                || txtMesA.getText().equals("")
                || txtAnoA.getText().equals("")
                || txtEnderecoA.getText().equals("")
                || txtTelefoneA.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            return;
            //||txtNomeA.getText().matches("^[a-zA-Z]+$")||txtEmailA.getText().matches("^[a-zA-Z]+$")||txtEmailA.getText().matches("^[a-zA-Z]+$")||txtSenhaA.getText().matches("^[a-zA-Z]+$")||txtDiaA.getText().matches("")||txtDiaA.getText().matches
        } else if (!txtCPFA.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do CPF deve conter apenas números.");
            return;
        } else if (!txtNomeA.getText().matches("^[\\p{L}\\s]+$")) {
            JOptionPane.showMessageDialog(null, "O campo do nome deve conter apenas letras.");
            return;
        } else if (!txtDiaA.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do dia deve conter apenas números.");
            return;
        } else if (!txtMesA.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do mês deve conter apenas números.");
            return;
        } else if (!txtAnoA.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do ano deve conter apenas números.");
            return;
        } else if (txtCPFA.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "O CPF deve conter 11 números.");
            return;
        } else if (txtNomeA.getText().length() >= 80) {
            JOptionPane.showMessageDialog(null, "O Nome deve conter menos que 80 caracteres.");
            return;
        } else if (txtDiaA.getText().length() != 2) {
            JOptionPane.showMessageDialog(null, "O dia deve conter 2 números.");
            return;
        } else if (txtMesA.getText().length() != 2) {
            JOptionPane.showMessageDialog(null, "O mês deve conter 2 números.");
            return;
        } else if (txtAnoA.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "O ano deve conter 4 números.");
            return;
        } else if (!txtTelefoneA.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do telefone deve conter apenas números.");
            return;
        } else {
            a.setCPFAluno(txtCPFA.getText());
        }
        a.setNomeA(txtNomeA.getText());
        a.setEmailA(txtEmailA.getText());
        a.setSenhaA(txtSenhaA.getText());

        try {
            int dia = Integer.parseInt(txtDiaA.getText());
            int mes = Integer.parseInt(txtMesA.getText());
            int ano = Integer.parseInt(txtAnoA.getText());

            if (dia <= 0 || dia > 31) {
                JOptionPane.showMessageDialog(null, "Dia inválido. Deve estar entre 1 e 31.");
                return;
            }
            if (mes <= 0 || mes > 12) {
                JOptionPane.showMessageDialog(null, "Mês inválido. Deve estar entre 1 e 12.");
                return;
            }
            if (ano < 1900 || ano > LocalDate.now().getYear()) {
                JOptionPane.showMessageDialog(null, "Ano inválido. Deve estar entre 1900 e o ano atual.");
                return;
            }
            LocalDate data = LocalDate.of(ano, mes, dia);

            String dataFormatada = data.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            a.setData_NascA(dataFormatada);

            System.out.println("Data de nascimento cadastrada: " + dataFormatada);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Dia, mês e ano devem ser números válidos.");
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Data inválida.");
        }
        int idResponsavel = getIdFromComboBox(boxRespA, Id_Responsavel);

        if (idResponsavel != -1) {
            a.setId_Responsavel(idResponsavel);
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao obter ID do responsável.");
            return;
        }

        a.setGeneroA(boxGeneroA.getSelectedItem().toString());
        a.setEnderecoA(txtEnderecoA.getText());
        a.setTelefoneA(txtTelefoneA.getText());
        try {
            dao.cadastrarAluno(a);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar aluno: Classe não encontrada.");
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar aluno: SQL exception.");
        }
        TelaConsAluno Tca = new TelaConsAluno();
        Tca.setVisible(true);
        dispose();
    }//GEN-LAST:event_btInserirAActionPerformed

    private void boxRespAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRespAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRespAActionPerformed

    private void txtCPFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFAActionPerformed

    private void boxGeneroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGeneroA;
    private javax.swing.JComboBox<String> boxRespA;
    private javax.swing.JButton btInserirA;
    private javax.swing.JButton btLimparA;
    private javax.swing.JButton btnVoltarCadA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTextField txtAnoA;
    private javax.swing.JTextField txtCPFA;
    private javax.swing.JTextField txtDiaA;
    private javax.swing.JTextField txtEmailA;
    private javax.swing.JTextField txtEnderecoA;
    private javax.swing.JTextField txtMesA;
    private javax.swing.JTextField txtNomeA;
    private javax.swing.JTextField txtSenhaA;
    private javax.swing.JTextField txtTelefoneA;
    // End of variables declaration//GEN-END:variables
}
