/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Horarios;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sisescola_java.Objetos1.*;

/**
 *
 * @author Matheus
 */
public class TelaDesescalar extends javax.swing.JFrame {

    private void carregarProfessoresHorarios() throws ClassNotFoundException {
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProfessorEscalado.getModel();
        modeloTabela.setRowCount(0);  // Limpa a tabela antes de carregar os novos resultados

        // SQL para consultar os dados da tabela Professores_Horarios, incluindo o CPF do professor
        String sql = "SELECT p.Id_Professor, p.Nome, p.CPF, h.Id_Horario, h.Inicio, h.Dia_Semana, h.Turno "
                + "FROM Professores p "
                + "INNER JOIN Professores_Horarios ph ON p.Id_Professor = ph.Professor_ID "
                + "INNER JOIN Horarios h ON ph.Horario_ID = h.Id_Horario";

        try (Connection con = ConnectionFactory.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

            ResultSet rs = ps.executeQuery(); // Executa a consulta SQL

            // Itera sobre o ResultSet e adiciona os resultados na tabela
            while (rs.next()) {
                // Depuração para verificar o que está sendo retornado do ResultSet
                System.out.println("ID Professor: " + rs.getInt("Id_Professor"));
                System.out.println("Nome: " + rs.getString("Nome"));
                System.out.println("CPF: " + rs.getString("CPF"));
                System.out.println("ID Horário: " + rs.getInt("Id_Horario"));
                System.out.println("Inicio: " + rs.getTime("Inicio"));
                System.out.println("Dia Semana: " + rs.getString("Dia_Semana"));
                System.out.println("Turno: " + rs.getString("Turno"));

                modeloTabela.addRow(new Object[]{
                    rs.getInt("Id_Professor"), // ID do professor
                    rs.getString("Nome"), // Nome do professor
                    rs.getString("CPF"), // CPF do professor
                    rs.getInt("Id_Horario"), // ID do horário
                    rs.getTime("Inicio"), // Horário de início
                    rs.getString("Dia_Semana"), // Dia da semana
                    rs.getString("Turno") // Turno
                });
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar horários: " + ex.getMessage());
        }
    }

    /**
     * Creates new form TelaDesescalar
     */
    public TelaDesescalar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalC = new javax.swing.JPanel();
        btnVoltarCadA = new javax.swing.JButton();
        lblIDTurma = new javax.swing.JLabel();
        btDesescalar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfessorEscalado = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        lblNomeE1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desescalar Professor");

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        btnVoltarCadA.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarCadA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarCadA.setToolTipText("Voltar");
        btnVoltarCadA.setBorder(null);
        btnVoltarCadA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarCadAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarCadAMouseExited(evt);
            }
        });
        btnVoltarCadA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadAActionPerformed(evt);
            }
        });

        lblIDTurma.setFont(new java.awt.Font("Segoe UI", 1, 2)); // NOI18N
        lblIDTurma.setForeground(new java.awt.Color(2, 48, 71));
        lblIDTurma.setText("IDTURMA");

        btDesescalar.setBackground(new java.awt.Color(142, 202, 230));
        btDesescalar.setForeground(new java.awt.Color(142, 202, 230));
        btDesescalar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeTurma2.png"))); // NOI18N
        btDesescalar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btDesescalar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDesescalarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDesescalarMouseExited(evt);
            }
        });
        btDesescalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesescalarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(2, 48, 71));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Desescalar Professor");

        tblProfessorEscalado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Prof", "CPF", "Nome", "Id_Horario", "Horario", "DiaSemana", "Turno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProfessorEscalado);
        if (tblProfessorEscalado.getColumnModel().getColumnCount() > 0) {
            tblProfessorEscalado.getColumnModel().getColumn(0).setMaxWidth(80);
            tblProfessorEscalado.getColumnModel().getColumn(1).setMinWidth(90);
            tblProfessorEscalado.getColumnModel().getColumn(1).setMaxWidth(90);
            tblProfessorEscalado.getColumnModel().getColumn(3).setMinWidth(0);
            tblProfessorEscalado.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblProfessorEscalado.getColumnModel().getColumn(3).setMaxWidth(0);
            tblProfessorEscalado.getColumnModel().getColumn(4).setMaxWidth(100);
            tblProfessorEscalado.getColumnModel().getColumn(6).setMaxWidth(90);
        }

        lblNomeE1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeE1.setForeground(new java.awt.Color(2, 48, 71));
        lblNomeE1.setText("Digite o nome ou CPF do professor:");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarCadA)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblNomeE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(lblIDTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                        .addComponent(btDesescalar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(39, 39, 39)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltarCadA))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeE1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDesescalar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(lblIDTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomCLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Desescalar");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopoCLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarCadAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadAMouseEntered
        btnVoltarCadA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarCadAMouseEntered

    private void btnVoltarCadAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadAMouseExited
        btnVoltarCadA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarCadAMouseExited

    private void btnVoltarCadAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadAActionPerformed
        try {
            TelaEscalar t = new TelaEscalar();
            t.setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaDesescalar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaDesescalar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVoltarCadAActionPerformed

    private void btDesescalarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesescalarMouseEntered
        btDesescalar.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btDesescalarMouseEntered

    private void btDesescalarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesescalarMouseExited
        btDesescalar.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btDesescalarMouseExited

    private void btDesescalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesescalarActionPerformed
        // Obtém a linha selecionada da tabela
        int selectedRow = tblProfessorEscalado.getSelectedRow();

        if (selectedRow != -1) {
            // Obtém os valores das células
            Object professorIdObj = tblProfessorEscalado.getValueAt(selectedRow, 0); // Coluna 0: ID_Professor
            Object nomeProfessorObj = tblProfessorEscalado.getValueAt(selectedRow, 2);  // Coluna 3: Nome
            Object horarioIdObj = tblProfessorEscalado.getValueAt(selectedRow, 3);    // Coluna 4: Horário

            // Imprime os valores para depuração
            System.out.println("professorIdObj: " + professorIdObj);
            System.out.println("nomeProfessorObj: " + nomeProfessorObj);
            System.out.println("horarioIdObj: " + horarioIdObj);

            int professorId = 0;
            int horarioId = 0;

            try {
                // Verifica e converte o ID do professor
                if (professorIdObj instanceof Integer) {
                    professorId = (int) professorIdObj;
                } else if (professorIdObj instanceof String) {
                    // Caso seja string (talvez o nome do professor), tente converter para número
                    try {
                        professorId = Integer.parseInt((String) professorIdObj);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Erro: ID de professor inválido.");
                        return; // Sai do método em caso de erro
                    }
                }

                // Verifica e converte o ID do horário
                if (horarioIdObj instanceof Integer) {
                    horarioId = (int) horarioIdObj;
                } else if (horarioIdObj instanceof String) {
                    try {
                        // Imprime para depuração
                        System.out.println("Tentando converter horárioIdObj: " + horarioIdObj);
                        horarioId = Integer.parseInt((String) horarioIdObj);
                    } catch (NumberFormatException e) {
                        // Mostra o erro e retorna
                        JOptionPane.showMessageDialog(this, "Erro: ID de horário inválido.");
                        return;
                    }
                }

                // Verifica se o horarioId foi atribuído corretamente
                if (horarioId == 0) {
                    JOptionPane.showMessageDialog(this, "Erro: ID de horário inválido.");
                    return; // Retorna se o ID for inválido
                }

                // Chama o método para remover a escala
                EscalaDAO dao = new EscalaDAO();
                dao.removerEscala(professorId, horarioId);

                // Atualiza a tabela após a remoção
                DefaultTableModel modeloTabela = (DefaultTableModel) tblProfessorEscalado.getModel();
                modeloTabela.setRowCount(0); // Limpa a tabela

            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro ao desescalar: " + e.getMessage());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erro: ID de professor ou horário inválido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um professor para desescalar.");
        }
    }//GEN-LAST:event_btDesescalarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cpfOuNome = txtBuscar.getText();  // Obtém o CPF ou nome do professor da interface
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProfessorEscalado.getModel();
        modeloTabela.setRowCount(0); // Limpa a tabela antes de carregar os novos resultados

        String sql = "SELECT p.Id_Professor, p.Nome, p.CPF, h.Id_Horario, h.Inicio, h.Dia_Semana, h.Turno "
                + "FROM Professores p "
                + "INNER JOIN Professores_Horarios ph ON p.Id_Professor = ph.Professor_ID "
                + "INNER JOIN Horarios h ON ph.Horario_ID = h.Id_Horario "
                + "WHERE p.Nome LIKE ? OR p.CPF = ?";  // Pesquisa por nome ou CPF, sem ID de horário

        try (Connection con = ConnectionFactory.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, "%" + cpfOuNome + "%");
            ps.setString(2, cpfOuNome);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modeloTabela.addRow(new Object[]{
                    rs.getInt("Id_Professor"),
                    rs.getString("CPF"),
                    rs.getString("Nome"),
                    rs.getInt("h.Id_Horario"),
                    rs.getString("Inicio"),
                    rs.getString("Dia_Semana"),
                    rs.getString("Turno")
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro na consulta: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaDesescalar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDesescalar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDesescalar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDesescalar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDesescalar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDesescalar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDesescalar;
    private javax.swing.JButton btnVoltarCadA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblIDTurma;
    private javax.swing.JLabel lblNomeE1;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTable tblProfessorEscalado;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
