/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Horarios;

import sisescola_java.paginasis.Professores.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sisescola_java.paginasis.TelaCRUDS;

/**
 *
 * @author Matheus
 */
public class TelaHorarios extends javax.swing.JFrame {
    /**
     * Creates new form TelaProfessores
     */
    public TelaHorarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVoltarA = new javax.swing.JButton();
        pnlTopoP = new javax.swing.JPanel();
        lblTopoP = new javax.swing.JLabel();
        pnlPrincipalP = new javax.swing.JPanel();
        btCadastrarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btEscala = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btConsultarP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btExcluirP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btAlterarP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btVoltarP = new javax.swing.JButton();
        btEscalarMate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlBottomP = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btVoltarA.setBackground(new java.awt.Color(142, 202, 230));
        btVoltarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltarA.setForeground(new java.awt.Color(2, 48, 71));
        btVoltarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btVoltarA.setBorder(null);
        btVoltarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarAMouseExited(evt);
            }
        });
        btVoltarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarAActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horários");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoP.setBackground(new java.awt.Color(2, 48, 71));

        lblTopoP.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoP.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoP.setText("Horários");
        lblTopoP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoPLayout = new javax.swing.GroupLayout(pnlTopoP);
        pnlTopoP.setLayout(pnlTopoPLayout);
        pnlTopoPLayout.setHorizontalGroup(
            pnlTopoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopoPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTopoP)
                .addGap(300, 300, 300))
        );
        pnlTopoPLayout.setVerticalGroup(
            pnlTopoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTopoP)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlPrincipalP.setBackground(new java.awt.Color(142, 202, 230));
        pnlPrincipalP.setForeground(new java.awt.Color(204, 204, 204));

        btCadastrarP.setBackground(new java.awt.Color(142, 202, 230));
        btCadastrarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrarP.setForeground(new java.awt.Color(2, 48, 71));
        btCadastrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Cadastar.png"))); // NOI18N
        btCadastrarP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 3, true));
        btCadastrarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadastrarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCadastrarPMouseExited(evt);
            }
        });
        btCadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarPActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(2, 48, 71));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("Cadastrar");

        btEscala.setBackground(new java.awt.Color(142, 202, 230));
        btEscala.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEscala.setForeground(new java.awt.Color(2, 48, 71));
        btEscala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Escala.png"))); // NOI18N
        btEscala.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 3, true));
        btEscala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btEscalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btEscalaMouseExited(evt);
            }
        });
        btEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscalaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Escala");

        btConsultarP.setBackground(new java.awt.Color(142, 202, 230));
        btConsultarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConsultarP.setForeground(new java.awt.Color(2, 48, 71));
        btConsultarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Consultar.png"))); // NOI18N
        btConsultarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 48, 71), 3));
        btConsultarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btConsultarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btConsultarPMouseExited(evt);
            }
        });
        btConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Consultar");

        btExcluirP.setBackground(new java.awt.Color(142, 202, 230));
        btExcluirP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExcluirP.setForeground(new java.awt.Color(2, 48, 71));
        btExcluirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Excluir.png"))); // NOI18N
        btExcluirP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 48, 71), 3));
        btExcluirP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExcluirPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExcluirPMouseExited(evt);
            }
        });
        btExcluirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirPActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Excluir");

        btAlterarP.setBackground(new java.awt.Color(142, 202, 230));
        btAlterarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAlterarP.setForeground(new java.awt.Color(2, 48, 71));
        btAlterarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Alterar.png"))); // NOI18N
        btAlterarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 48, 71), 3));
        btAlterarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAlterarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlterarPMouseExited(evt);
            }
        });
        btAlterarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alterar");

        btVoltarP.setBackground(new java.awt.Color(142, 202, 230));
        btVoltarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltarP.setForeground(new java.awt.Color(2, 48, 71));
        btVoltarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btVoltarP.setToolTipText("Voltar");
        btVoltarP.setBorder(null);
        btVoltarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarPMouseExited(evt);
            }
        });
        btVoltarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarPActionPerformed(evt);
            }
        });

        btEscalarMate.setBackground(new java.awt.Color(142, 202, 230));
        btEscalarMate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEscalarMate.setForeground(new java.awt.Color(2, 48, 71));
        btEscalarMate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/IconeMateriasp.png"))); // NOI18N
        btEscalarMate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 3, true));
        btEscalarMate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btEscalarMateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btEscalarMateMouseExited(evt);
            }
        });
        btEscalarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscalarMateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Matérias");

        javax.swing.GroupLayout pnlPrincipalPLayout = new javax.swing.GroupLayout(pnlPrincipalP);
        pnlPrincipalP.setLayout(pnlPrincipalPLayout);
        pnlPrincipalPLayout.setHorizontalGroup(
            pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarP)
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAlterarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastrarP)))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4)))
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEscala)
                            .addComponent(btEscalarMate)))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel7)))
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btExcluirP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btConsultarP))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(139, 139, 139))))
        );
        pnlPrincipalPLayout.setVerticalGroup(
            pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCadastrarP)
                            .addComponent(btConsultarP)))
                    .addComponent(btVoltarP)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEscala)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAlterarP)
                            .addComponent(btExcluirP)))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEscalarMate)))
                .addContainerGap())
        );

        pnlBottomP.setBackground(new java.awt.Color(2, 48, 71));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomPLayout = new javax.swing.GroupLayout(pnlBottomP);
        pnlBottomP.setLayout(pnlBottomPLayout);
        pnlBottomPLayout.setHorizontalGroup(
            pnlBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomPLayout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addGap(310, 310, 310))
        );
        pnlBottomPLayout.setVerticalGroup(
            pnlBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btCadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarPActionPerformed
        TelaCadHorario tcp = new TelaCadHorario();
        tcp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCadastrarPActionPerformed

    private void btAlterarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarPActionPerformed
        TelaAltHorario tah = new TelaAltHorario();
        tah.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAlterarPActionPerformed

    private void btVoltarAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarAMouseEntered
        btVoltarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btVoltarAMouseEntered

    private void btVoltarAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarAMouseExited
        btVoltarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btVoltarAMouseExited

    private void btVoltarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarAActionPerformed
        TelaCRUDS CRUD = new TelaCRUDS();
        CRUD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarAActionPerformed

    private void btCadastrarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarPMouseEntered
        btCadastrarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btCadastrarPMouseEntered

    private void btCadastrarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarPMouseExited
        btCadastrarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btCadastrarPMouseExited

    private void btAlterarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarPMouseEntered
        btAlterarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btAlterarPMouseEntered

    private void btAlterarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarPMouseExited
        btAlterarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btAlterarPMouseExited

    private void btEscalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEscalaMouseEntered
        btEscala.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btEscalaMouseEntered

    private void btEscalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEscalaMouseExited
        btEscala.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btEscalaMouseExited

    private void btConsultarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarPMouseEntered
        btConsultarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btConsultarPMouseEntered

    private void btConsultarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarPMouseExited
        btConsultarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btConsultarPMouseExited

    private void btExcluirPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirPMouseEntered
        btExcluirP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btExcluirPMouseEntered

    private void btExcluirPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirPMouseExited
        btExcluirP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btExcluirPMouseExited

    private void btVoltarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarPMouseEntered
        btVoltarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btVoltarPMouseEntered

    private void btVoltarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarPMouseExited
        btVoltarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btVoltarPMouseExited

    private void btVoltarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarPActionPerformed
        TelaCRUDS CRUD = new TelaCRUDS();
        CRUD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarPActionPerformed

    private void btEscalarMateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEscalarMateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btEscalarMateMouseEntered

    private void btEscalarMateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEscalarMateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btEscalarMateMouseExited

    private void btEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscalaActionPerformed
        try {
            TelaEscalar esc = new TelaEscalar();
            esc.setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaHorarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btEscalaActionPerformed

    private void btEscalarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscalarMateActionPerformed
        try {
            TelaEscalarMate tea = new TelaEscalarMate();
            tea.setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaHorarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btEscalarMateActionPerformed

    private void btExcluirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirPActionPerformed
        TelaDelHorario tdh = new TelaDelHorario();
        tdh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btExcluirPActionPerformed

    private void btConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarPActionPerformed
        TelaConHorario tch = new TelaConHorario();
        tch.setVisible(true);
        dispose();
    }//GEN-LAST:event_btConsultarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHorarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarP;
    private javax.swing.JButton btCadastrarP;
    private javax.swing.JButton btConsultarP;
    private javax.swing.JButton btEscala;
    private javax.swing.JButton btEscalarMate;
    private javax.swing.JButton btExcluirP;
    private javax.swing.JButton btVoltarA;
    private javax.swing.JButton btVoltarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblTopoP;
    private javax.swing.JPanel pnlBottomP;
    private javax.swing.JPanel pnlPrincipalP;
    private javax.swing.JPanel pnlTopoP;
    // End of variables declaration//GEN-END:variables
}
