/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Professores;

import sisescola_java.paginasis.Adminisrador.*;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sisescola_java.Objetos1.*;
import sisescola_java.paginasis.Telalogin;

/**
 *
 * @author Matheus
 */
public class TelaCadProf extends javax.swing.JFrame {    
    /**
     * Creates new form TelaCadAdm
     */
    public TelaCadProf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBottomAdm = new javax.swing.JPanel();
        lblBottomAdm = new javax.swing.JLabel();
        lblBottomAdm2 = new javax.swing.JLabel();
        pnlTopAdm = new javax.swing.JPanel();
        lblTopAdm2 = new javax.swing.JLabel();
        pnlPrincipalADM = new javax.swing.JPanel();
        txtCPFProf = new javax.swing.JTextField();
        lblCPFAdm = new javax.swing.JLabel();
        lblNomeAdm = new javax.swing.JLabel();
        txtNomeProf = new javax.swing.JTextField();
        txtEmailProf = new javax.swing.JTextField();
        lblEmailAdm = new javax.swing.JLabel();
        lblSenhaAdm = new javax.swing.JLabel();
        txtSenhaProf = new javax.swing.JTextField();
        lblNascAdm = new javax.swing.JLabel();
        txtDiaProf = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtMesProf = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtAnoProf = new javax.swing.JTextField();
        lblEnderecoAdm = new javax.swing.JLabel();
        txtEnderecoProf = new javax.swing.JTextField();
        lblTelAdm = new javax.swing.JLabel();
        txtTelefoneProf = new javax.swing.JTextField();
        lblGeneroAdm = new javax.swing.JLabel();
        boxGeneroProf = new javax.swing.JComboBox<>();
        btInserirProf = new javax.swing.JButton();
        lblCadAdm = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btLimparProf = new javax.swing.JButton();
        btnVoltarCadAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Professor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBottomAdm.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomAdm.setForeground(new java.awt.Color(0, 0, 153));
        pnlBottomAdm.setPreferredSize(new java.awt.Dimension(800, 100));

        lblBottomAdm.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomAdm.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomAdm.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomAdm.setText("SYST");

        lblBottomAdm2.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        lblBottomAdm2.setForeground(new java.awt.Color(142, 202, 230));
        lblBottomAdm2.setText("edu");

        javax.swing.GroupLayout pnlBottomAdmLayout = new javax.swing.GroupLayout(pnlBottomAdm);
        pnlBottomAdm.setLayout(pnlBottomAdmLayout);
        pnlBottomAdmLayout.setHorizontalGroup(
            pnlBottomAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomAdmLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(lblBottomAdm2)
                .addGap(0, 0, 0)
                .addComponent(lblBottomAdm)
                .addGap(310, 310, 310))
        );
        pnlBottomAdmLayout.setVerticalGroup(
            pnlBottomAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomAdmLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBottomAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomAdm)
                    .addComponent(lblBottomAdm2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlTopAdm.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopAdm.setForeground(new java.awt.Color(0, 0, 153));
        pnlTopAdm.setPreferredSize(new java.awt.Dimension(800, 100));

        lblTopAdm2.setBackground(new java.awt.Color(251, 133, 0));
        lblTopAdm2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopAdm2.setForeground(new java.awt.Color(251, 133, 0));
        lblTopAdm2.setText("Cadastro");

        javax.swing.GroupLayout pnlTopAdmLayout = new javax.swing.GroupLayout(pnlTopAdm);
        pnlTopAdm.setLayout(pnlTopAdmLayout);
        pnlTopAdmLayout.setHorizontalGroup(
            pnlTopAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopAdmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTopAdm2)
                .addGap(304, 304, 304))
        );
        pnlTopAdmLayout.setVerticalGroup(
            pnlTopAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopAdmLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTopAdm2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlPrincipalADM.setBackground(new java.awt.Color(142, 202, 230));

        txtCPFProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCPFProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFProfActionPerformed(evt);
            }
        });

        lblCPFAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCPFAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblCPFAdm.setText("CPF:");

        lblNomeAdm.setBackground(new java.awt.Color(2, 48, 71));
        lblNomeAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblNomeAdm.setText("Nome:");

        txtNomeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfActionPerformed(evt);
            }
        });

        lblEmailAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmailAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblEmailAdm.setText("E-mail:");

        lblSenhaAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenhaAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblSenhaAdm.setText("Senha:");

        lblNascAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNascAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblNascAdm.setText("Nascimento:");

        txtDiaProf.setForeground(new java.awt.Color(2, 48, 71));
        txtDiaProf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(2, 48, 71));
        jLabel46.setText("/");

        txtMesProf.setForeground(new java.awt.Color(2, 48, 71));
        txtMesProf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMesProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesProfActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(2, 48, 71));
        jLabel47.setText("/");

        txtAnoProf.setForeground(new java.awt.Color(2, 48, 71));
        txtAnoProf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnoProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAnoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoProfActionPerformed(evt);
            }
        });

        lblEnderecoAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEnderecoAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblEnderecoAdm.setText("Endereço:");

        lblTelAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblTelAdm.setText("Telefone:");

        lblGeneroAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGeneroAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblGeneroAdm.setText("Gênero:");

        boxGeneroProf.setForeground(new java.awt.Color(2, 48, 71));
        boxGeneroProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homem", "Mulher", "Homem Trans", "Mulher Trans", "Não Binário", "Outro" }));
        boxGeneroProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boxGeneroProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxGeneroProfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boxGeneroProfMouseExited(evt);
            }
        });

        btInserirProf.setBackground(new java.awt.Color(142, 202, 230));
        btInserirProf.setForeground(new java.awt.Color(2, 48, 71));
        btInserirProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastar.png"))); // NOI18N
        btInserirProf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 5, true));
        btInserirProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btInserirProfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btInserirProfMouseExited(evt);
            }
        });
        btInserirProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirProfActionPerformed(evt);
            }
        });

        lblCadAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCadAdm.setForeground(new java.awt.Color(2, 48, 71));
        lblCadAdm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadAdm.setText("CADASTRAR PPROFESSOR");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(2, 48, 71));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("LIMPAR");

        btLimparProf.setBackground(new java.awt.Color(142, 202, 230));
        btLimparProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar.png"))); // NOI18N
        btLimparProf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btLimparProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparProfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparProfMouseExited(evt);
            }
        });
        btLimparProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparProfActionPerformed(evt);
            }
        });

        btnVoltarCadAdm.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarCadAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarCadAdm.setBorder(null);
        btnVoltarCadAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarCadAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarCadAdmMouseExited(evt);
            }
        });
        btnVoltarCadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalADMLayout = new javax.swing.GroupLayout(pnlPrincipalADM);
        pnlPrincipalADM.setLayout(pnlPrincipalADMLayout);
        pnlPrincipalADMLayout.setHorizontalGroup(
            pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                .addComponent(btnVoltarCadAdm)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                                .addComponent(lblNascAdm)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMesProf, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                                    .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNomeAdm)
                                        .addComponent(lblEmailAdm)
                                        .addComponent(lblCPFAdm))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmailProf, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCPFProf, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                                    .addComponent(lblSenhaAdm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSenhaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblGeneroAdm))
                            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                                .addComponent(lblEnderecoAdm)
                                .addGap(18, 18, 18)
                                .addComponent(txtEnderecoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                                .addComponent(lblTelAdm)
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxGeneroProf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefoneProf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInserirProf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btLimparProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalADMLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(62, 62, 62)))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalADMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCadAdm)
                        .addGap(71, 71, 71))))
        );
        pnlPrincipalADMLayout.setVerticalGroup(
            pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPFAdm)
                    .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtCPFProf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAdm)
                    .addComponent(txtNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAdm)
                    .addComponent(txtEmailProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAdm)
                    .addComponent(txtSenhaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascAdm)
                    .addComponent(txtDiaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel46)
                    .addComponent(txtMesProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecoAdm)
                    .addComponent(txtEnderecoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelAdm)
                    .addComponent(txtTelefoneProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxGeneroProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeneroAdm))
                .addGap(90, 90, 90))
            .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                .addGroup(pnlPrincipalADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltarCadAdm))
                    .addGroup(pnlPrincipalADMLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblCadAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btInserirProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparProf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBottomAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTopAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipalADM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTopAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalADM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void txtCPFProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFProfActionPerformed

    private void txtNomeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProfActionPerformed

    private void txtMesProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesProfActionPerformed

    private void txtAnoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoProfActionPerformed

    private void boxGeneroProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroProfMouseEntered
        boxGeneroProf.setForeground(new Color(251, 133, 0));
    }//GEN-LAST:event_boxGeneroProfMouseEntered

    private void boxGeneroProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroProfMouseExited
        boxGeneroProf.setForeground(new Color(2, 48, 71));
    }//GEN-LAST:event_boxGeneroProfMouseExited

    private void btInserirProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirProfMouseEntered
        btInserirProf.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btInserirProfMouseEntered

    private void btInserirProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirProfMouseExited
        btInserirProf.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btInserirProfMouseExited

    private void btInserirProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirProfActionPerformed
        Professor prof = new Professor();
        ProfessorDAO dao = new ProfessorDAO();
        if (txtCPFProf.getText().equals("")
            || txtNomeProf.getText().equals("")
            || txtEmailProf.getText().equals("")
            || txtSenhaProf.getText().equals("")
            || txtDiaProf.getText().equals("")
            || txtMesProf.getText().equals("")
            || txtAnoProf.getText().equals("")
            || txtEnderecoProf.getText().equals("")
            || txtTelefoneProf.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            return;
            //||txtNomeA.getText().matches("^[a-zA-Z]+$")||txtEmailA.getText().matches("^[a-zA-Z]+$")||txtEmailA.getText().matches("^[a-zA-Z]+$")||txtSenhaA.getText().matches("^[a-zA-Z]+$")||txtDiaA.getText().matches("")||txtDiaA.getText().matches
        } else if (!txtCPFProf.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do CPF deve conter apenas números.");
            return;
        } else if (!txtNomeProf.getText().matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(null, "O campo do nome deve conter apenas letras.");
            return;
        } else if (!txtDiaProf.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do dia deve conter apenas números.");
            return;
        } else if (!txtMesProf.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do mês deve conter apenas números.");
            return;
        } else if (!txtAnoProf.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do ano deve conter apenas números.");
            return;
        } else if (!txtTelefoneProf.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do telfone deve conter apenas números sem formatação.");
            return;
        } else if (txtCPFProf.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "O CPF deve conter 11 números.");
            return;
        } else if (txtNomeProf.getText().length() >= 80) {
            JOptionPane.showMessageDialog(null, "O Nome deve conter menos que 80 caracteres.");
            return;
        } else if (txtDiaProf.getText().length() != 2) {
            JOptionPane.showMessageDialog(null, "O dia deve conter 2 números.");
            return;
        } else if (txtMesProf.getText().length() != 2) {
            JOptionPane.showMessageDialog(null, "O mês deve conter 2 números.");
            return;
        } else if (txtAnoProf.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "O ano deve conter 4 números.");
            return;
        } else if (txtTelefoneProf.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "O telefone deve conter 11 números.");
            return;
        } else {
            prof.setCPFp(txtCPFProf.getText());
        }
        prof.setNomep(txtNomeProf.getText());
        prof.setEmailp(txtEmailProf.getText());
        prof.setSenhap(txtSenhaProf.getText());

        try {
            int dia = Integer.parseInt(txtDiaProf.getText());
            int mes = Integer.parseInt(txtMesProf.getText());
            int ano = Integer.parseInt(txtAnoProf.getText());
            if (dia > 31 || dia == 0) {
                JOptionPane.showMessageDialog(null, "Dia inválido");
                return;
            } else if (mes > 12 || mes == 0) {
                JOptionPane.showMessageDialog(null, "Mês inválido");
                return;
            } else if (ano < 1944 || ano > 2024) {
                JOptionPane.showMessageDialog(null, "Ano inválido");
                return;
            } else {
                LocalDate data = LocalDate.of(ano, mes, dia);
                String dataFormatada = data.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                prof.setData_Nascp(dataFormatada);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Dia, mês e ano devem ser números válidos.");
            return;
        }
        prof.setEnderecop(txtEnderecoProf.getText());
        prof.setTelefonep(txtTelefoneProf.getText());

        prof.setGenerop(boxGeneroProf.getSelectedItem().toString());
        try {
            dao.cadastrarProf(prof);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadProf.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar administrador: Classe não encontrada.");
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadProf.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar administrador: SQL exception.");
        }
    }//GEN-LAST:event_btInserirProfActionPerformed

    private void btLimparProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparProfMouseEntered
        btLimparProf.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btLimparProfMouseEntered

    private void btLimparProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparProfMouseExited
        btLimparProf.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btLimparProfMouseExited

    private void btLimparProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparProfActionPerformed
        txtCPFProf.setText("");
        txtNomeProf.setText("");
        txtEmailProf.setText("");
        txtSenhaProf.setText("");
        txtDiaProf.setText("");
        txtMesProf.setText("");
        txtAnoProf.setText("");
        txtEnderecoProf.setText("");
        txtTelefoneProf.setText("");
        boxGeneroProf.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparProfActionPerformed

    private void btnVoltarCadAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadAdmMouseEntered
        btnVoltarCadAdm.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarCadAdmMouseEntered

    private void btnVoltarCadAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadAdmMouseExited
        btnVoltarCadAdm.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarCadAdmMouseExited

    private void btnVoltarCadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadAdmActionPerformed
        TelaProfessores tlprof = new TelaProfessores();
        tlprof.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarCadAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGeneroProf;
    private javax.swing.JButton btInserirProf;
    private javax.swing.JButton btLimparProf;
    private javax.swing.JButton btnVoltarCadAdm;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel lblBottomAdm;
    private javax.swing.JLabel lblBottomAdm2;
    private javax.swing.JLabel lblCPFAdm;
    private javax.swing.JLabel lblCadAdm;
    private javax.swing.JLabel lblEmailAdm;
    private javax.swing.JLabel lblEnderecoAdm;
    private javax.swing.JLabel lblGeneroAdm;
    private javax.swing.JLabel lblNascAdm;
    private javax.swing.JLabel lblNomeAdm;
    private javax.swing.JLabel lblSenhaAdm;
    private javax.swing.JLabel lblTelAdm;
    private javax.swing.JLabel lblTopAdm2;
    private javax.swing.JPanel pnlBottomAdm;
    private javax.swing.JPanel pnlPrincipalADM;
    private javax.swing.JPanel pnlTopAdm;
    private javax.swing.JTextField txtAnoProf;
    private javax.swing.JTextField txtCPFProf;
    private javax.swing.JTextField txtDiaProf;
    private javax.swing.JTextField txtEmailProf;
    private javax.swing.JTextField txtEnderecoProf;
    private javax.swing.JTextField txtMesProf;
    private javax.swing.JTextField txtNomeProf;
    private javax.swing.JTextField txtSenhaProf;
    private javax.swing.JTextField txtTelefoneProf;
    // End of variables declaration//GEN-END:variables
}
