/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Professores;

import java.awt.Color;
import sisescola_java.paginasis.TelaCRUDS;

/**
 *
 * @author Matheus
 */
public class TelaProfessores extends javax.swing.JFrame {
    /**
     * Creates new form TelaProfessores
     */
    public TelaProfessores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVoltarA = new javax.swing.JButton();
        pnlTopoP = new javax.swing.JPanel();
        lblTopoP = new javax.swing.JLabel();
        pnlPrincipalP = new javax.swing.JPanel();
        btCadastrarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btImprimirP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btConsultarP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btExcluirP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btAlterarP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btVoltarP = new javax.swing.JButton();
        btImprimirP1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlBottomP = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btVoltarA.setBackground(new java.awt.Color(142, 202, 230));
        btVoltarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltarA.setForeground(new java.awt.Color(2, 48, 71));
        btVoltarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btVoltarA.setBorder(null);
        btVoltarA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarAMouseExited(evt);
            }
        });
        btVoltarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarAActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professores");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoP.setBackground(new java.awt.Color(2, 48, 71));

        lblTopoP.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoP.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoP.setText("Professores");
        lblTopoP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoPLayout = new javax.swing.GroupLayout(pnlTopoP);
        pnlTopoP.setLayout(pnlTopoPLayout);
        pnlTopoPLayout.setHorizontalGroup(
            pnlTopoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoPLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblTopoP)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        pnlTopoPLayout.setVerticalGroup(
            pnlTopoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoP)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlPrincipalP.setBackground(new java.awt.Color(142, 202, 230));
        pnlPrincipalP.setForeground(new java.awt.Color(204, 204, 204));

        btCadastrarP.setBackground(new java.awt.Color(142, 202, 230));
        btCadastrarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrarP.setForeground(new java.awt.Color(2, 48, 71));
        btCadastrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Cadastar.png"))); // NOI18N
        btCadastrarP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 3, true));
        btCadastrarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadastrarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCadastrarPMouseExited(evt);
            }
        });
        btCadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarPActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(2, 48, 71));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("Cadastrar");

        btImprimirP.setBackground(new java.awt.Color(142, 202, 230));
        btImprimirP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btImprimirP.setForeground(new java.awt.Color(2, 48, 71));
        btImprimirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Imprimir.png"))); // NOI18N
        btImprimirP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 3, true));
        btImprimirP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImprimirPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImprimirPMouseExited(evt);
            }
        });
        btImprimirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Imprimir");

        btConsultarP.setBackground(new java.awt.Color(142, 202, 230));
        btConsultarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConsultarP.setForeground(new java.awt.Color(2, 48, 71));
        btConsultarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Consultar.png"))); // NOI18N
        btConsultarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 48, 71), 3));
        btConsultarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btConsultarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btConsultarPMouseExited(evt);
            }
        });
        btConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Consultar");

        btExcluirP.setBackground(new java.awt.Color(142, 202, 230));
        btExcluirP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExcluirP.setForeground(new java.awt.Color(2, 48, 71));
        btExcluirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Excluir.png"))); // NOI18N
        btExcluirP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 48, 71), 3));
        btExcluirP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExcluirPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExcluirPMouseExited(evt);
            }
        });
        btExcluirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirPActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Excluir");

        btAlterarP.setBackground(new java.awt.Color(142, 202, 230));
        btAlterarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAlterarP.setForeground(new java.awt.Color(2, 48, 71));
        btAlterarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Alterar.png"))); // NOI18N
        btAlterarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 48, 71), 3));
        btAlterarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAlterarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlterarPMouseExited(evt);
            }
        });
        btAlterarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alterar");

        btVoltarP.setBackground(new java.awt.Color(142, 202, 230));
        btVoltarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltarP.setForeground(new java.awt.Color(2, 48, 71));
        btVoltarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btVoltarP.setToolTipText("Voltar");
        btVoltarP.setBorder(null);
        btVoltarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarPMouseExited(evt);
            }
        });
        btVoltarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarPActionPerformed(evt);
            }
        });

        btImprimirP1.setBackground(new java.awt.Color(142, 202, 230));
        btImprimirP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btImprimirP1.setForeground(new java.awt.Color(2, 48, 71));
        btImprimirP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Escala.png"))); // NOI18N
        btImprimirP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 3, true));
        btImprimirP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImprimirP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImprimirP1MouseExited(evt);
            }
        });
        btImprimirP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirP1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Grade Horária");

        javax.swing.GroupLayout pnlPrincipalPLayout = new javax.swing.GroupLayout(pnlPrincipalP);
        pnlPrincipalP.setLayout(pnlPrincipalPLayout);
        pnlPrincipalPLayout.setHorizontalGroup(
            pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarP)
                .addGap(73, 73, 73)
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btAlterarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadastrarP))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImprimirP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btImprimirP1))
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btExcluirP)
                            .addComponent(btConsultarP))
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(148, 148, 148))))
        );
        pnlPrincipalPLayout.setVerticalGroup(
            pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btCadastrarP))
                            .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btConsultarP))))
                    .addComponent(btVoltarP)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImprimirP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAlterarP)
                            .addComponent(btExcluirP)))
                    .addGroup(pnlPrincipalPLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImprimirP1)))
                .addContainerGap())
        );

        pnlBottomP.setBackground(new java.awt.Color(2, 48, 71));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomPLayout = new javax.swing.GroupLayout(pnlBottomP);
        pnlBottomP.setLayout(pnlBottomPLayout);
        pnlBottomPLayout.setHorizontalGroup(
            pnlBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addGap(310, 310, 310))
        );
        pnlBottomPLayout.setVerticalGroup(
            pnlBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBottomPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btCadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarPActionPerformed
        TelaCadProf tcp = new TelaCadProf();
        tcp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCadastrarPActionPerformed

    private void btAlterarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarPActionPerformed
        TelaAltProf tap = new TelaAltProf();
        tap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAlterarPActionPerformed

    private void btVoltarAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarAMouseEntered
        btVoltarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btVoltarAMouseEntered

    private void btVoltarAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarAMouseExited
        btVoltarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btVoltarAMouseExited

    private void btVoltarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarAActionPerformed
        TelaCRUDS CRUD = new TelaCRUDS();
        CRUD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarAActionPerformed

    private void btCadastrarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarPMouseEntered
        btCadastrarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btCadastrarPMouseEntered

    private void btCadastrarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarPMouseExited
        btCadastrarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btCadastrarPMouseExited

    private void btAlterarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarPMouseEntered
        btAlterarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btAlterarPMouseEntered

    private void btAlterarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarPMouseExited
        btAlterarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btAlterarPMouseExited

    private void btImprimirPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImprimirPMouseEntered
        btImprimirP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btImprimirPMouseEntered

    private void btImprimirPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImprimirPMouseExited
        btImprimirP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btImprimirPMouseExited

    private void btConsultarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarPMouseEntered
        btConsultarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btConsultarPMouseEntered

    private void btConsultarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarPMouseExited
        btConsultarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btConsultarPMouseExited

    private void btExcluirPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirPMouseEntered
        btExcluirP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btExcluirPMouseEntered

    private void btExcluirPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirPMouseExited
        btExcluirP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btExcluirPMouseExited

    private void btVoltarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarPMouseEntered
        btVoltarP.setBackground(new Color(251,133,0));
    }//GEN-LAST:event_btVoltarPMouseEntered

    private void btVoltarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarPMouseExited
        btVoltarP.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btVoltarPMouseExited

    private void btVoltarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarPActionPerformed
        TelaCRUDS CRUD = new TelaCRUDS();
        CRUD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarPActionPerformed

    private void btImprimirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirPActionPerformed
        TelaImpProfessor tip = new TelaImpProfessor();
        tip.setVisible(true);
        dispose();
    }//GEN-LAST:event_btImprimirPActionPerformed

    private void btConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarPActionPerformed
        TelaConsProf tcp = new TelaConsProf();
        tcp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btConsultarPActionPerformed

    private void btExcluirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirPActionPerformed
        TelaDelProf tdp = new TelaDelProf();
        tdp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btExcluirPActionPerformed

    private void btImprimirP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImprimirP1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirP1MouseEntered

    private void btImprimirP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImprimirP1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirP1MouseExited

    private void btImprimirP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirP1ActionPerformed
        TelaGradeProfessor tgh = new TelaGradeProfessor();
        tgh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btImprimirP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarP;
    private javax.swing.JButton btCadastrarP;
    private javax.swing.JButton btConsultarP;
    private javax.swing.JButton btExcluirP;
    private javax.swing.JButton btImprimirP;
    private javax.swing.JButton btImprimirP1;
    private javax.swing.JButton btVoltarA;
    private javax.swing.JButton btVoltarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblTopoP;
    private javax.swing.JPanel pnlBottomP;
    private javax.swing.JPanel pnlPrincipalP;
    private javax.swing.JPanel pnlTopoP;
    // End of variables declaration//GEN-END:variables
}
