/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Responsavel;

import sisescola_java.paginasis.Aluno.*;
import java.awt.Color;
import java.sql.*;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sisescola_java.Objetos1.*;

/**
 *
 * @author Matheus
 */
public class TelaAltResp extends javax.swing.JFrame {

    public void boxGeneros() {
        try {
            ResponsavelDAO rpd = new ResponsavelDAO();
            ResultSet rs = rpd.listarGeneros();

            while (rs.next()) {
                String genero = rs.getString("Genero");
                if (boxGeneroAResp.getItemCount() > 0 && !boxGeneroAResp.getItemAt(0).equals(genero)) {
                    boxGeneroAResp.addItem(genero);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na combobox do gênero: " + e);
        }
    }

    public void btconsulta(String pesquisa) {
        ResponsavelDAO rdao = new ResponsavelDAO();
        try {
            // Verifica se a string de pesquisa é um CPF (números com 11 dígitos)
            if (pesquisa.matches("\\d{11}")) {
                // Consulta pelo CPF
                for (Responsavel R : rdao.btconsultar(null, pesquisa)) {

                    txtCPFAResp.setText(R.getCPFResp());
                    txtNomeAResp.setText(R.getNomeResp());
                    txtEmailAResp.setText(R.getEmailResp());
                    txtSenhaAResp.setText("");
                    if (R.getData_NascResp() != null) {
                        LocalDate data = LocalDate.parse(R.getData_NascResp(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                        txtDiaAResp.setText(String.valueOf(data.getDayOfMonth()));
                        txtMesAResp.setText(String.valueOf(data.getMonthValue()));
                        txtAnoAResp.setText(String.valueOf(data.getYear()));
                    }
                    txtEnderecoAResp.setText(R.getEnderecoResp());
                    txtTelefoneAResp.setText(R.getTelefoneResp());
                    boxGeneroAResp.setSelectedItem(String.valueOf(R.getGeneroResp()));
                }
            } else {
                // Consulta pelo Nome
                for (Responsavel R : rdao.btconsultar(pesquisa, null)) {

                    txtCPFAResp.setText(R.getCPFResp());
                    txtNomeAResp.setText(R.getNomeResp());
                    txtEmailAResp.setText(R.getEmailResp());
                    txtSenhaAResp.setText("");
                    if (R.getData_NascResp() != null) {
                        LocalDate data = LocalDate.parse(R.getData_NascResp(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                        txtDiaAResp.setText(String.valueOf(data.getDayOfMonth()));
                        txtMesAResp.setText(String.valueOf(data.getMonthValue()));
                        txtAnoAResp.setText(String.valueOf(data.getYear()));
                    }
                    txtEnderecoAResp.setText(R.getEnderecoResp());
                    txtTelefoneAResp.setText(R.getTelefoneResp());
                    boxGeneroAResp.setSelectedItem(String.valueOf(R.getGeneroResp()));

                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaConsResp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form TelaAltAluno
     */
    public TelaAltResp() {
        initComponents();
        boxGeneros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCPFAResp = new javax.swing.JTextField();
        txtEmailAResp = new javax.swing.JTextField();
        txtNomeAResp = new javax.swing.JTextField();
        txtDiaAResp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMesAResp = new javax.swing.JTextField();
        txtAnoAResp = new javax.swing.JTextField();
        txtEnderecoAResp = new javax.swing.JTextField();
        txtTelefoneAResp = new javax.swing.JTextField();
        boxGeneroAResp = new javax.swing.JComboBox<>();
        btnVoltarAltResp = new javax.swing.JButton();
        btAlterarResp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btLimparResp = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSenhaAResp = new javax.swing.JTextField();
        btPesquisaAltResp = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtPesquisarAltResp = new javax.swing.JTextField();
        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar Responsável");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("Insira o Nome ou CPF do responsável:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setText("Endereço:");

        jLabel5.setBackground(new java.awt.Color(2, 48, 71));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setText("Nascimento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setText("E-mail:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 48, 71));
        jLabel9.setText("Telefone:");

        txtCPFAResp.setEditable(false);
        txtCPFAResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCPFAResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFARespActionPerformed(evt);
            }
        });

        txtNomeAResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeARespActionPerformed(evt);
            }
        });

        txtDiaAResp.setForeground(new java.awt.Color(2, 48, 71));
        txtDiaAResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaAResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 48, 71));
        jLabel10.setText("/");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(2, 48, 71));
        jLabel11.setText("/");

        txtMesAResp.setForeground(new java.awt.Color(2, 48, 71));
        txtMesAResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesAResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMesAResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesARespActionPerformed(evt);
            }
        });

        txtAnoAResp.setForeground(new java.awt.Color(2, 48, 71));
        txtAnoAResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnoAResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAnoAResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoARespActionPerformed(evt);
            }
        });

        boxGeneroAResp.setForeground(new java.awt.Color(2, 48, 71));
        boxGeneroAResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Homem Trans", "Mulher Trans", "Não-Binário", "Outro" }));
        boxGeneroAResp.setSelectedItem(-1);
        boxGeneroAResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boxGeneroAResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxGeneroARespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boxGeneroARespMouseExited(evt);
            }
        });
        boxGeneroAResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroARespActionPerformed(evt);
            }
        });

        btnVoltarAltResp.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarAltResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarAltResp.setToolTipText("Voltar");
        btnVoltarAltResp.setBorder(null);
        btnVoltarAltResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarAltRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarAltRespMouseExited(evt);
            }
        });
        btnVoltarAltResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAltRespActionPerformed(evt);
            }
        });

        btAlterarResp.setBackground(new java.awt.Color(142, 202, 230));
        btAlterarResp.setForeground(new java.awt.Color(2, 48, 71));
        btAlterarResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        btAlterarResp.setToolTipText("Alterar");
        btAlterarResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 5, true));
        btAlterarResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAlterarRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlterarRespMouseExited(evt);
            }
        });
        btAlterarResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarRespActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 48, 71));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ALTERAR RESPONSÁVEL");

        btLimparResp.setBackground(new java.awt.Color(142, 202, 230));
        btLimparResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar.png"))); // NOI18N
        btLimparResp.setToolTipText("Limpar");
        btLimparResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btLimparResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparRespMouseExited(evt);
            }
        });
        btLimparResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparRespActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 48, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIMPAR");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 48, 71));
        jLabel14.setText("Senha:");

        btPesquisaAltResp.setText("PESQUISAR");
        btPesquisaAltResp.setToolTipText("Pesquisar");
        btPesquisaAltResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaAltRespActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 48, 71));
        jLabel15.setText("CPF:");

        txtPesquisarAltResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarAltRespActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarAltResp)
                .addGap(38, 38, 38)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisarAltResp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisaAltResp)
                        .addContainerGap())
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailAResp)
                                    .addComponent(txtNomeAResp)))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiaAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMesAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnoAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPFAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnderecoAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefoneAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxGeneroAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtSenhaAResp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAlterarResp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btLimparResp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(152, 152, 152))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(85, 85, 85))))))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(btnVoltarAltResp)
                        .addContainerGap(451, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPesquisarAltResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisaAltResp))
                        .addGap(30, 30, 30)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtCPFAResp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNomeAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEmailAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtSenhaAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDiaAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMesAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnoAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtEnderecoAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTelefoneAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxGeneroAResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(btAlterarResp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimparResp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Alterar");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addGap(352, 352, 352))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeARespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeARespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeARespActionPerformed

    private void boxGeneroARespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroARespMouseEntered
        boxGeneroAResp.setForeground(new Color(251, 133, 0));
    }//GEN-LAST:event_boxGeneroARespMouseEntered

    private void boxGeneroARespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroARespMouseExited
        boxGeneroAResp.setForeground(new Color(2, 48, 71));
    }//GEN-LAST:event_boxGeneroARespMouseExited

    private void btnVoltarAltRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarAltRespMouseEntered
        btnVoltarAltResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarAltRespMouseEntered

    private void btnVoltarAltRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarAltRespMouseExited
        btnVoltarAltResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarAltRespMouseExited

    private void btnVoltarAltRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAltRespActionPerformed
        TelaResponsavel r = new TelaResponsavel();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarAltRespActionPerformed

    private void btAlterarRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarRespMouseEntered
        btAlterarResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btAlterarRespMouseEntered

    private void btAlterarRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarRespMouseExited
        btAlterarResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btAlterarRespMouseExited

    private void btAlterarRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarRespActionPerformed
        Responsavel r = new Responsavel();
        ResponsavelDAO dao = new ResponsavelDAO();
        if (txtCPFAResp.getText().equals("")
                || txtNomeAResp.getText().equals("")
                || txtEmailAResp.getText().equals("")
                || txtDiaAResp.getText().equals("")
                || txtMesAResp.getText().equals("")
                || txtAnoAResp.getText().equals("")
                || txtEnderecoAResp.getText().equals("")
                || txtTelefoneAResp.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            return;
        } else if (!txtCPFAResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do CPF deve conter apenas números.");
            return;
        } else if (!txtNomeAResp.getText().matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(null, "O campo do nome deve conter apenas letras.");
            return;
        } else if (!txtDiaAResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do dia deve conter apenas números.");
            return;
        } else if (!txtMesAResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do mês deve conter apenas números.");
            return;
        } else if (!txtAnoAResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do ano deve conter apenas números.");
            return;
        } else if (!txtTelefoneAResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do telefone deve conter apenas números sem formatação.");
            return;
        } else if (txtCPFAResp.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "O CPF deve conter 11 números.");
            return;
        } else if (txtNomeAResp.getText().length() >= 80) {
            JOptionPane.showMessageDialog(null, "O Nome deve conter menos que 80 caracteres.");
            return;
        } else if (txtDiaAResp.getText().length() > 2) {
            JOptionPane.showMessageDialog(null, "Dia inválido.");
            return;
        } else if (txtMesAResp.getText().length() > 2) {
            JOptionPane.showMessageDialog(null, "Mês inválido");
            return;
        } else if (txtAnoAResp.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "O ano deve conter 4 números.");
            return;
        } else if (txtTelefoneAResp.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "O telefone deve conter 11 números.");
            return;
        } else {
            r.setCPFResp(txtCPFAResp.getText());
        }

        r.setNomeResp(txtNomeAResp.getText());
        r.setEmailResp(txtEmailAResp.getText());
        r.setSenhaResp(txtSenhaAResp.getText());

        try {
            int dia = Integer.parseInt(txtDiaAResp.getText());
            int mes = Integer.parseInt(txtMesAResp.getText());
            int ano = Integer.parseInt(txtAnoAResp.getText());

            // Tentativa de criar a data diretamente
            try {
                LocalDate data = LocalDate.of(ano, mes, dia);
                String dataFormatada = data.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                r.setData_NascResp(dataFormatada);  // Assumindo que r é o objeto Responsavel
            } catch (DateTimeException e) {
                // Caso a data seja inválida
                JOptionPane.showMessageDialog(null, "Data inválida: " + e.getMessage());
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Dia, mês e ano devem ser números válidos.");
            return;
        }
        r.setEnderecoResp(txtEnderecoAResp.getText());
        r.setTelefoneResp(txtTelefoneAResp.getText());
        r.setGeneroResp(boxGeneroAResp.getSelectedItem().toString());
        try {
            if (txtSenhaAResp.getText().isBlank() || txtSenhaAResp.getText().isEmpty()) {
                dao.AtualizarRespSemSenha(r);
            } else {
                dao.AtualizarRespComSenha(r);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadResp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao atualizar aluno: Classe não encontrada.");
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadResp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao atualizar aluno: SQL exception.");
        }
        txtCPFAResp.setText("");
        txtNomeAResp.setText("");
        txtEmailAResp.setText("");
        txtSenhaAResp.setText("");
        txtDiaAResp.setText("");
        txtMesAResp.setText("");
        txtAnoAResp.setText("");
        txtEnderecoAResp.setText("");
        txtTelefoneAResp.setText("");
        boxGeneroAResp.setSelectedIndex(0);
        txtPesquisarAltResp.setText("");
    }//GEN-LAST:event_btAlterarRespActionPerformed

    private void btLimparRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparRespMouseEntered
        btLimparResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btLimparRespMouseEntered

    private void btLimparRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparRespMouseExited
        btLimparResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btLimparRespMouseExited

    private void btLimparRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparRespActionPerformed
        txtCPFAResp.setText("");
        txtNomeAResp.setText("");
        txtEmailAResp.setText("");
        txtSenhaAResp.setText("");
        txtDiaAResp.setText("");
        txtMesAResp.setText("");
        txtAnoAResp.setText("");
        txtEnderecoAResp.setText("");
        txtTelefoneAResp.setText("");
        boxGeneroAResp.setSelectedIndex(0);
        txtPesquisarAltResp.setText("");

    }//GEN-LAST:event_btLimparRespActionPerformed

    private void btPesquisaAltRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaAltRespActionPerformed
        btconsulta(txtPesquisarAltResp.getText());
    }//GEN-LAST:event_btPesquisaAltRespActionPerformed

    private void txtAnoARespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoARespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoARespActionPerformed

    private void txtMesARespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesARespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesARespActionPerformed

    private void boxGeneroARespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroARespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroARespActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void txtPesquisarAltRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarAltRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarAltRespActionPerformed

    private void txtCPFARespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFARespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFARespActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAltResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAltResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAltResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAltResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAltResp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGeneroAResp;
    private javax.swing.JButton btAlterarResp;
    private javax.swing.JButton btLimparResp;
    private javax.swing.JButton btPesquisaAltResp;
    private javax.swing.JButton btnVoltarAltResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTextField txtAnoAResp;
    private javax.swing.JTextField txtCPFAResp;
    private javax.swing.JTextField txtDiaAResp;
    private javax.swing.JTextField txtEmailAResp;
    private javax.swing.JTextField txtEnderecoAResp;
    private javax.swing.JTextField txtMesAResp;
    private javax.swing.JTextField txtNomeAResp;
    private javax.swing.JTextField txtPesquisarAltResp;
    private javax.swing.JTextField txtSenhaAResp;
    private javax.swing.JTextField txtTelefoneAResp;
    // End of variables declaration//GEN-END:variables
}
