/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Responsavel;

import sisescola_java.paginasis.Aluno.*;
import sisescola_java.Objetos1.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaCadResp extends javax.swing.JFrame {
    public void boxGeneros() {
        try {
            AlunoDAO ald = new AlunoDAO();
            ResultSet rs = ald.listarGeneros();

            while (rs.next()) {
                String genero = rs.getString("Genero");
                // Verifica se o gênero já está na JComboBox
                boolean existe = false;
                for (int i = 0; i < boxGeneroResp.getItemCount(); i++) {
                    if (boxGeneroResp.getItemAt(i).equals(genero)) {
                        existe = true;
                        break;
                    }
                }
                if (!existe) {
                    boxGeneroResp.addItem(genero);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na combobox do gênero: " + e);
        }
    }

    public void selecionarGenero(String genero) {
        for (int i = 0; i < boxGeneroResp.getItemCount(); i++) {
            if (boxGeneroResp.getItemAt(i).equals(genero)) {
                boxGeneroResp.setSelectedIndex(i);
                return;
            }
        }
        // Se não encontrar o gênero, desmarcar a seleção
        boxGeneroResp.setSelectedIndex(-1);
    }

    /**
     * Creates new form TelaCadALuno
     */
    public TelaCadResp() {
        initComponents();
        boxGeneros();
        //listarResponsaveis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        pnlPrincipalC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCPFResp = new javax.swing.JTextField();
        txtEmailResp = new javax.swing.JTextField();
        txtNomeResp = new javax.swing.JTextField();
        txtDiaResp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMesResp = new javax.swing.JTextField();
        txtAnoResp = new javax.swing.JTextField();
        txtEnderecoResp = new javax.swing.JTextField();
        txtTelefoneResp = new javax.swing.JTextField();
        boxGeneroResp = new javax.swing.JComboBox<>();
        btnVoltarCadResp = new javax.swing.JButton();
        btInserirResp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btLimparResp = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSenhaResp = new javax.swing.JTextField();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Responsável");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Cadastrar");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("CPF:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setText("Endereço:");

        jLabel5.setBackground(new java.awt.Color(2, 48, 71));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setText("Nascimento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setText("E-mail:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 48, 71));
        jLabel9.setText("Telefone:");

        txtCPFResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCPFResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFRespActionPerformed(evt);
            }
        });

        txtNomeResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRespActionPerformed(evt);
            }
        });

        txtDiaResp.setForeground(new java.awt.Color(2, 48, 71));
        txtDiaResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 48, 71));
        jLabel10.setText("/");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(2, 48, 71));
        jLabel11.setText("/");

        txtMesResp.setForeground(new java.awt.Color(2, 48, 71));
        txtMesResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMesResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesRespActionPerformed(evt);
            }
        });

        txtAnoResp.setForeground(new java.awt.Color(2, 48, 71));
        txtAnoResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnoResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAnoResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoRespActionPerformed(evt);
            }
        });

        boxGeneroResp.setForeground(new java.awt.Color(2, 48, 71));
        boxGeneroResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Homem Trans", "Mulher Trans", "Não Binário", "Outro" }));
        boxGeneroResp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boxGeneroResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boxGeneroRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boxGeneroRespMouseExited(evt);
            }
        });
        boxGeneroResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGeneroRespActionPerformed(evt);
            }
        });

        btnVoltarCadResp.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarCadResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarCadResp.setToolTipText("Voltar");
        btnVoltarCadResp.setBorder(null);
        btnVoltarCadResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarCadRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarCadRespMouseExited(evt);
            }
        });
        btnVoltarCadResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadRespActionPerformed(evt);
            }
        });

        btInserirResp.setBackground(new java.awt.Color(142, 202, 230));
        btInserirResp.setForeground(new java.awt.Color(2, 48, 71));
        btInserirResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastar.png"))); // NOI18N
        btInserirResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 5, true));
        btInserirResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btInserirRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btInserirRespMouseExited(evt);
            }
        });
        btInserirResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirRespActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 48, 71));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CADASTRAR RESPONSÁVEL");

        btLimparResp.setBackground(new java.awt.Color(142, 202, 230));
        btLimparResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar.png"))); // NOI18N
        btLimparResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btLimparResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparRespMouseExited(evt);
            }
        });
        btLimparResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparRespActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 48, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIMPAR");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 48, 71));
        jLabel14.setText("Senha:");

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarCadResp)
                .addGap(49, 49, 49)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiaResp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMesResp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmailResp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtCPFResp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeResp, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txtSenhaResp, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnderecoResp))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxGeneroResp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefoneResp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btInserirResp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btLimparResp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(185, 185, 185))))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCPFResp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmailResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtSenhaResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiaResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(txtMesResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEnderecoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTelefoneResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxGeneroResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(btnVoltarCadResp)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btInserirResp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparResp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesRespActionPerformed

    private void txtAnoRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoRespActionPerformed

    private void txtNomeRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRespActionPerformed

    private void btInserirRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirRespMouseEntered
        btInserirResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btInserirRespMouseEntered

    private void btInserirRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirRespMouseExited
        btInserirResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btInserirRespMouseExited

    private void btnVoltarCadRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadRespActionPerformed
        TelaResponsavel a = new TelaResponsavel();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarCadRespActionPerformed

    private void btLimparRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparRespActionPerformed
        txtCPFResp.setText("");
        txtNomeResp.setText("");
        txtEmailResp.setText("");
        txtSenhaResp.setText("");
        txtDiaResp.setText("");
        txtMesResp.setText("");
        txtAnoResp.setText("");
        txtEnderecoResp.setText("");
        txtTelefoneResp.setText("");
        boxGeneroResp.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparRespActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void boxGeneroRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroRespMouseEntered
        
    }//GEN-LAST:event_boxGeneroRespMouseEntered

    private void boxGeneroRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxGeneroRespMouseExited
        
    }//GEN-LAST:event_boxGeneroRespMouseExited

    private void btLimparRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparRespMouseEntered
        btLimparResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btLimparRespMouseEntered

    private void btLimparRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparRespMouseExited
        btLimparResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btLimparRespMouseExited

    private void btnVoltarCadRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadRespMouseEntered
        btnVoltarCadResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarCadRespMouseEntered

    private void btnVoltarCadRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarCadRespMouseExited
        btnVoltarCadResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarCadRespMouseExited

    private void btInserirRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirRespActionPerformed
        Responsavel r = new Responsavel();
        ResponsavelDAO dao = new ResponsavelDAO();
        if (txtCPFResp.getText().equals("")
                || txtNomeResp.getText().equals("")
                || txtEmailResp.getText().equals("")
                || txtSenhaResp.getText().equals("")
                || txtDiaResp.getText().equals("")
                || txtMesResp.getText().equals("")
                || txtAnoResp.getText().equals("")
                || txtEnderecoResp.getText().equals("")
                || txtTelefoneResp.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            return;
            //||txtNomeA.getText().matches("^[a-zA-Z]+$")||txtEmailA.getText().matches("^[a-zA-Z]+$")||txtEmailA.getText().matches("^[a-zA-Z]+$")||txtSenhaA.getText().matches("^[a-zA-Z]+$")||txtDiaA.getText().matches("")||txtDiaA.getText().matches
        } else if (!txtCPFResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do CPF deve conter apenas números.");
            return;
        } else if (!txtNomeResp.getText().matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(null, "O campo do nome deve conter apenas letras.");
            return;
        } else if (!txtDiaResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do dia deve conter apenas números.");
            return;
        } else if (!txtMesResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do mês deve conter apenas números.");
            return;
        } else if (!txtAnoResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do ano deve conter apenas números.");
            return;
        } else if (txtCPFResp.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "O CPF deve conter 11 números.");
            return;
        } else if (txtNomeResp.getText().length() >= 80) {
            JOptionPane.showMessageDialog(null, "O Nome deve conter menos que 80 caracteres.");
            return;
        } else if (txtDiaResp.getText().length() != 2) {
            JOptionPane.showMessageDialog(null, "O dia deve conter 2 números.");
            return;
        } else if (txtMesResp.getText().length() != 2) {
            JOptionPane.showMessageDialog(null, "O mês deve conter 2 números.");
            return;
        } else if (txtAnoResp.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "O ano deve conter 4 números.");
            return;
        } else if (!txtTelefoneResp.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O campo do telefone deve conter apenas números.");
            return;
        } else {
            r.setCPFResp(txtCPFResp.getText());
        }
        r.setNomeResp(txtNomeResp.getText());
        r.setEmailResp(txtEmailResp.getText());
        r.setSenhaResp(txtSenhaResp.getText());

        try {
            int dia = Integer.parseInt(txtDiaResp.getText());
            int mes = Integer.parseInt(txtMesResp.getText());
            int ano = Integer.parseInt(txtAnoResp.getText());
            if (dia > 31 || dia == 0) {
                JOptionPane.showMessageDialog(null, "Dia inválido");
                return;
            } else if (mes > 12 || mes == 0) {
                JOptionPane.showMessageDialog(null, "Mês inválido");
                return;
            } else if (ano < 1944 || ano > 2024) {
                JOptionPane.showMessageDialog(null, "Ano inválido");
                return;
            } else {
                LocalDate data = LocalDate.of(ano, mes, dia);
                String dataFormatada = data.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                r.setData_NascResp(dataFormatada);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Dia, mês e ano devem ser números válidos.");
            return;
        }

        r.setGeneroResp(boxGeneroResp.getSelectedItem().toString());
        r.setEnderecoResp(txtEnderecoResp.getText());
        r.setTelefoneResp(txtTelefoneResp.getText());
        try {
            dao.cadastrarResp(r);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadResp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar responsável: Classe não encontrada.");
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadResp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar responsável: SQL exception.");
        }
        TelaConsResp Tcr = new TelaConsResp();
        Tcr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btInserirRespActionPerformed

    private void txtCPFRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFRespActionPerformed

    private void boxGeneroRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroRespActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadResp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadResp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxGeneroResp;
    private javax.swing.JButton btInserirResp;
    private javax.swing.JButton btLimparResp;
    private javax.swing.JButton btnVoltarCadResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTextField txtAnoResp;
    private javax.swing.JTextField txtCPFResp;
    private javax.swing.JTextField txtDiaResp;
    private javax.swing.JTextField txtEmailResp;
    private javax.swing.JTextField txtEnderecoResp;
    private javax.swing.JTextField txtMesResp;
    private javax.swing.JTextField txtNomeResp;
    private javax.swing.JTextField txtSenhaResp;
    private javax.swing.JTextField txtTelefoneResp;
    // End of variables declaration//GEN-END:variables
}
