/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Responsavel;

import sisescola_java.paginasis.Professores.*;
import sisescola_java.paginasis.Aluno.*;
import java.awt.*;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import sisescola_java.Objetos1.Aluno;
import sisescola_java.Objetos1.AlunoDAO;
import sisescola_java.Objetos1.Professor;
import sisescola_java.Objetos1.ProfessorDAO;
import sisescola_java.Objetos1.Responsavel;
import sisescola_java.Objetos1.ResponsavelDAO;
import sisescola_java.paginasis.Responsavel.TelaConsResp;

/**
 *
 * @author Matheus
 */
public class TelaImpResp extends javax.swing.JFrame {

    public void imprimirTela() {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                // Define o painel para impressão
                JPanel painelParaImprimir = painelInfoAluno; // Substitua pelo nome correto do painel

                // Define a área de recorte (101 pixels à direita e 380 pixels do topo)
                int x = 101;
                int y = 50;
                int width = 518;
                int height = 470;

                g2d.setClip(x, y, width, height);

                // Renderiza apenas a área especificada do painel
                painelParaImprimir.paint(g2d);

                return Printable.PAGE_EXISTS;
            }
        });

        // Exibe a caixa de diálogo para o usuário selecionar a impressora
        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException e) {
                JOptionPane.showMessageDialog(this, "Erro ao tentar imprimir: " + e.getMessage());
            }
        }
    }

    public void btconsulta(String pesquisa) {
        ResponsavelDAO rdao = new ResponsavelDAO();
        try {
            // Verifica se a string de pesquisa é um CPF (números com 11 dígitos)
            if (pesquisa.matches("\\d{11}")) {
                // Consulta pelo CPF
                for (Responsavel r : rdao.btconsultar(null, pesquisa)) {

                    lblIDResp.setText(String.valueOf(r.getId_Resp()));
                    lblCPFResp.setText(r.getCPFResp());
                    lblNomeResp.setText(r.getNomeResp());
                    lblEmailResp.setText(r.getEmailResp());
                    lblNascResp.setText(r.getData_NascResp());
                    lblEnderecoResp.setText(r.getEnderecoResp());
                    lblTelefoneResp.setText(r.getTelefoneResp());
                    lblGeneroResp.setText(r.getGeneroResp());
                }
            } else {
                // Consulta pelo Nome
                for (Responsavel r : rdao.btconsultar(pesquisa, null)) {

                    lblIDResp.setText(String.valueOf(r.getId_Resp()));
                    lblCPFResp.setText(r.getCPFResp());
                    lblNomeResp.setText(r.getNomeResp());
                    lblEmailResp.setText(r.getEmailResp());
                    lblNascResp.setText(r.getData_NascResp());
                    lblEnderecoResp.setText(r.getEnderecoResp());
                    lblTelefoneResp.setText(r.getTelefoneResp());
                    lblGeneroResp.setText(r.getGeneroResp());
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaConsResp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public TelaImpResp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        painelInfoAluno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnVoltarExcA = new javax.swing.JButton();
        lblIDResp = new javax.swing.JLabel();
        lblNomeResp = new javax.swing.JLabel();
        lblEmailResp = new javax.swing.JLabel();
        lblNascResp = new javax.swing.JLabel();
        lblEnderecoResp = new javax.swing.JLabel();
        lblTelefoneResp = new javax.swing.JLabel();
        lblGeneroResp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCPFResp = new javax.swing.JLabel();
        txtNomeAlunoP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btpesquisade = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imprimir Responsável");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Imprimir");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        painelInfoAluno.setBackground(new java.awt.Color(142, 202, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setText("Endereço:");

        jLabel5.setBackground(new java.awt.Color(2, 48, 71));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setText("Nascimento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setText("E-mail:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 48, 71));
        jLabel9.setText("Telefone:");

        btnVoltarExcA.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarExcA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarExcA.setToolTipText("Voltar");
        btnVoltarExcA.setBorder(null);
        btnVoltarExcA.setName(""); // NOI18N
        btnVoltarExcA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarExcAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarExcAMouseExited(evt);
            }
        });
        btnVoltarExcA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarExcAActionPerformed(evt);
            }
        });

        lblIDResp.setBackground(new java.awt.Color(2, 48, 71));
        lblIDResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIDResp.setForeground(new java.awt.Color(2, 48, 71));
        lblIDResp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIDResp.setText("ID");
        lblIDResp.setToolTipText("");
        lblIDResp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIDResp.setPreferredSize(new java.awt.Dimension(18, 16));
        lblIDResp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblIDRespInputMethodTextChanged(evt);
            }
        });

        lblNomeResp.setBackground(new java.awt.Color(2, 48, 71));
        lblNomeResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNomeResp.setForeground(new java.awt.Color(2, 48, 71));
        lblNomeResp.setText("Nome");

        lblEmailResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmailResp.setForeground(new java.awt.Color(2, 48, 71));
        lblEmailResp.setText("Email");

        lblNascResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNascResp.setForeground(new java.awt.Color(2, 48, 71));
        lblNascResp.setText("Data de Nascimento");

        lblEnderecoResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEnderecoResp.setForeground(new java.awt.Color(2, 48, 71));
        lblEnderecoResp.setText("Endereço");

        lblTelefoneResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefoneResp.setForeground(new java.awt.Color(2, 48, 71));
        lblTelefoneResp.setText("Telefone");

        lblGeneroResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGeneroResp.setForeground(new java.awt.Color(2, 48, 71));
        lblGeneroResp.setText("Gênero");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 48, 71));
        jLabel15.setText("CPF:");

        lblCPFResp.setBackground(new java.awt.Color(2, 48, 71));
        lblCPFResp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCPFResp.setForeground(new java.awt.Color(2, 48, 71));
        lblCPFResp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPFResp.setText("CPF");
        lblCPFResp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblCPFRespInputMethodTextChanged(evt);
            }
        });

        txtNomeAlunoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoPActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 48, 71));
        jLabel10.setText("Nome ou CPF do resposável:");

        btpesquisade.setText("Pesquisar");
        btpesquisade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisadeActionPerformed(evt);
            }
        });

        btImprimir.setBackground(new java.awt.Color(142, 202, 230));
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/Imprimir.png"))); // NOI18N
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 48, 71));
        jLabel8.setText("Responsavel");

        javax.swing.GroupLayout painelInfoAlunoLayout = new javax.swing.GroupLayout(painelInfoAluno);
        painelInfoAluno.setLayout(painelInfoAlunoLayout);
        painelInfoAlunoLayout.setHorizontalGroup(
            painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInfoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarExcA)
                .addGap(45, 45, 45)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAlunoP, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btpesquisade))
                    .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                        .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblIDResp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNascResp))
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEnderecoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEmailResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTelefoneResp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCPFResp, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGeneroResp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImprimir)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelInfoAlunoLayout.setVerticalGroup(
            painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInfoAlunoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVoltarExcA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNomeAlunoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpesquisade))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIDResp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblCPFResp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                        .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lblNomeResp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblEmailResp))
                        .addGap(18, 18, 18)
                        .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblNascResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelInfoAlunoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btImprimir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEnderecoResp))
                .addGap(12, 12, 12)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTelefoneResp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInfoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblGeneroResp))
                .addGap(24, 24, 24))
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(painelInfoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelInfoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarExcAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarExcAMouseEntered
        btnVoltarExcA.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarExcAMouseEntered

    private void btnVoltarExcAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarExcAMouseExited
        btnVoltarExcA.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarExcAMouseExited

    private void btnVoltarExcAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarExcAActionPerformed
        TelaAluno a = new TelaAluno();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarExcAActionPerformed

    private void lblIDRespInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblIDRespInputMethodTextChanged

    }//GEN-LAST:event_lblIDRespInputMethodTextChanged

    private void lblCPFRespInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblCPFRespInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCPFRespInputMethodTextChanged

    private void btpesquisadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisadeActionPerformed
        btconsulta(txtNomeAlunoP.getText());
    }//GEN-LAST:event_btpesquisadeActionPerformed

    private void txtNomeAlunoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        imprimirTela();
    }//GEN-LAST:event_btImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImpResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImpResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImpResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImpResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImpResp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btnVoltarExcA;
    private javax.swing.JButton btpesquisade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblCPFResp;
    private javax.swing.JLabel lblEmailResp;
    private javax.swing.JLabel lblEnderecoResp;
    private javax.swing.JLabel lblGeneroResp;
    private javax.swing.JLabel lblIDResp;
    private javax.swing.JLabel lblNascResp;
    private javax.swing.JLabel lblNomeResp;
    private javax.swing.JLabel lblTelefoneResp;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel painelInfoAluno;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTextField txtNomeAlunoP;
    // End of variables declaration//GEN-END:variables
}
