/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisescola_java.paginasis.Responsavel;

import sisescola_java.paginasis.Aluno.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import sisescola_java.Objetos1.Responsavel;
import sisescola_java.Objetos1.ResponsavelDAO;

/**
 *
 * @author Matheus
 */
public class TelaDelResp extends javax.swing.JFrame {

    public void btconsulta(String pesquisa) {
        ResponsavelDAO rdao = new ResponsavelDAO();
        try {
            // Verifica se a string de pesquisa é um CPF (números com 11 dígitos)
            if (pesquisa.matches("\\d{11}")) {
                // Consulta pelo CPF
                for (Responsavel r : rdao.btconsultar(null, pesquisa)) {

                    lblIDResp.setText(String.valueOf(r.getId_Resp()));
                    lblCPFResp.setText(r.getCPFResp());
                    lblNomeResp.setText(r.getNomeResp());
                    lblEmailResp.setText(r.getEmailResp());
                    lblNascResp.setText(r.getData_NascResp());
                    lblEnderecoResp.setText(r.getEnderecoResp());
                    lblTelefoneResp.setText(r.getTelefoneResp());
                    lblGeneroResp.setText(r.getGeneroResp());
                }
            } else {
                // Consulta pelo Nome
                for (Responsavel r : rdao.btconsultar(pesquisa, null)) {

                    lblIDResp.setText(String.valueOf(r.getId_Resp()));
                    lblCPFResp.setText(r.getCPFResp());
                    lblNomeResp.setText(r.getNomeResp());
                    lblEmailResp.setText(r.getEmailResp());
                    lblNascResp.setText(r.getData_NascResp());
                    lblEnderecoResp.setText(r.getEnderecoResp());
                    lblTelefoneResp.setText(r.getTelefoneResp());
                    lblGeneroResp.setText(r.getGeneroResp());
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaConsResp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form TelaDelAluno
     */
    public TelaDelResp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopoC = new javax.swing.JPanel();
        lblTopoC = new javax.swing.JLabel();
        pnlPrincipalC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnVoltarExcResp = new javax.swing.JButton();
        btDeletarResp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btLimparResp = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblIDResp = new javax.swing.JLabel();
        lblNomeResp = new javax.swing.JLabel();
        lblEmailResp = new javax.swing.JLabel();
        lblNascResp = new javax.swing.JLabel();
        lblEnderecoResp = new javax.swing.JLabel();
        lblTelefoneResp = new javax.swing.JLabel();
        lblGeneroResp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblCPFResp = new javax.swing.JLabel();
        txtNomeRespP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btpesquisadeResp = new javax.swing.JButton();
        pnlBottomC = new javax.swing.JPanel();
        lblBottomC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Excluir Responsáveis");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopoC.setBackground(new java.awt.Color(2, 48, 71));
        pnlTopoC.setMinimumSize(new java.awt.Dimension(800, 100));

        lblTopoC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTopoC.setForeground(new java.awt.Color(251, 133, 0));
        lblTopoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopoC.setText("Excluir");
        lblTopoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTopoCLayout = new javax.swing.GroupLayout(pnlTopoC);
        pnlTopoC.setLayout(pnlTopoCLayout);
        pnlTopoCLayout.setHorizontalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlTopoCLayout.setVerticalGroup(
            pnlTopoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopoCLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlPrincipalC.setBackground(new java.awt.Color(142, 202, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 48, 71));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 48, 71));
        jLabel3.setText("Gênero:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 48, 71));
        jLabel4.setText("Endereço:");

        jLabel5.setBackground(new java.awt.Color(2, 48, 71));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 48, 71));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 48, 71));
        jLabel6.setText("Nascimento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 48, 71));
        jLabel7.setText("E-mail:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 48, 71));
        jLabel9.setText("Telefone:");

        btnVoltarExcResp.setBackground(new java.awt.Color(142, 202, 230));
        btnVoltarExcResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagensbotãopequeno/voltar.png"))); // NOI18N
        btnVoltarExcResp.setToolTipText("Voltar");
        btnVoltarExcResp.setBorder(null);
        btnVoltarExcResp.setName(""); // NOI18N
        btnVoltarExcResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarExcRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarExcRespMouseExited(evt);
            }
        });
        btnVoltarExcResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarExcRespActionPerformed(evt);
            }
        });

        btDeletarResp.setBackground(new java.awt.Color(142, 202, 230));
        btDeletarResp.setForeground(new java.awt.Color(2, 48, 71));
        btDeletarResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        btDeletarResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 48, 71), 5, true));
        btDeletarResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeletarRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDeletarRespMouseExited(evt);
            }
        });
        btDeletarResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarRespActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 48, 71));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("EXCLUIR RESPONSÁVEL");

        btLimparResp.setBackground(new java.awt.Color(142, 202, 230));
        btLimparResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar.png"))); // NOI18N
        btLimparResp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btLimparResp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparRespMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparRespMouseExited(evt);
            }
        });
        btLimparResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparRespActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 48, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIMPAR");

        lblIDResp.setBackground(new java.awt.Color(2, 48, 71));
        lblIDResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDResp.setForeground(new java.awt.Color(2, 48, 71));
        lblIDResp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIDResp.setText("ID");
        lblIDResp.setToolTipText("");
        lblIDResp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIDResp.setPreferredSize(new java.awt.Dimension(18, 16));
        lblIDResp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblIDRespInputMethodTextChanged(evt);
            }
        });

        lblNomeResp.setBackground(new java.awt.Color(2, 48, 71));
        lblNomeResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeResp.setForeground(new java.awt.Color(2, 48, 71));
        lblNomeResp.setText("Nome");

        lblEmailResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailResp.setForeground(new java.awt.Color(2, 48, 71));
        lblEmailResp.setText("Email");

        lblNascResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNascResp.setForeground(new java.awt.Color(2, 48, 71));
        lblNascResp.setText("Data de Nascimento");

        lblEnderecoResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnderecoResp.setForeground(new java.awt.Color(2, 48, 71));
        lblEnderecoResp.setText("Endereço");

        lblTelefoneResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefoneResp.setForeground(new java.awt.Color(2, 48, 71));
        lblTelefoneResp.setText("Telefone");

        lblGeneroResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGeneroResp.setForeground(new java.awt.Color(2, 48, 71));
        lblGeneroResp.setText("Gênero");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 48, 71));
        jLabel15.setText("CPF:");

        lblCPFResp.setBackground(new java.awt.Color(2, 48, 71));
        lblCPFResp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPFResp.setForeground(new java.awt.Color(2, 48, 71));
        lblCPFResp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPFResp.setText("CPF");
        lblCPFResp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblCPFRespInputMethodTextChanged(evt);
            }
        });

        txtNomeRespP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRespPActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 48, 71));
        jLabel10.setText("Nome ou CPF do responsável:");

        btpesquisadeResp.setText("Pesquisar");
        btpesquisadeResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisadeRespActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalCLayout = new javax.swing.GroupLayout(pnlPrincipalC);
        pnlPrincipalC.setLayout(pnlPrincipalCLayout);
        pnlPrincipalCLayout.setHorizontalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarExcResp)
                .addGap(45, 45, 45)
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNomeResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEmailResp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblCPFResp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNascResp))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblEnderecoResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblGeneroResp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTelefoneResp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblIDResp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDeletarResp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLimparResp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeRespP, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btpesquisadeResp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlPrincipalCLayout.setVerticalGroup(
            pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCLayout.createSequentialGroup()
                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnVoltarExcResp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNomeRespP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btpesquisadeResp))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDeletarResp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimparResp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalCLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblIDResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblCPFResp))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblNomeResp))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblEmailResp))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblNascResp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblEnderecoResp))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lblTelefoneResp))
                                .addGap(21, 21, 21)
                                .addGroup(pnlPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblGeneroResp))))))
                .addContainerGap())
        );

        pnlBottomC.setBackground(new java.awt.Color(2, 48, 71));
        pnlBottomC.setPreferredSize(new java.awt.Dimension(499, 100));

        lblBottomC.setBackground(new java.awt.Color(251, 133, 0));
        lblBottomC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBottomC.setForeground(new java.awt.Color(251, 133, 0));
        lblBottomC.setText("SYST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 202, 230));
        jLabel1.setText("edu");

        javax.swing.GroupLayout pnlBottomCLayout = new javax.swing.GroupLayout(pnlBottomC);
        pnlBottomC.setLayout(pnlBottomCLayout);
        pnlBottomCLayout.setHorizontalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lblBottomC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomCLayout.setVerticalGroup(
            pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBottomC)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomC, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addComponent(pnlPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTopoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBottomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarExcRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarExcRespMouseEntered
        btnVoltarExcResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btnVoltarExcRespMouseEntered

    private void btnVoltarExcRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarExcRespMouseExited
        btnVoltarExcResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btnVoltarExcRespMouseExited

    private void btnVoltarExcRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarExcRespActionPerformed
        TelaResponsavel a = new TelaResponsavel();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarExcRespActionPerformed

    private void btDeletarRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarRespMouseEntered
        btDeletarResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btDeletarRespMouseEntered

    private void btDeletarRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarRespMouseExited
        btDeletarResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btDeletarRespMouseExited

    private void btDeletarRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarRespActionPerformed
        ResponsavelDAO A = new ResponsavelDAO();
        String nome = lblNomeResp.getText();
        String cpf = lblCPFResp.getText();

        if ((nome.isEmpty() || nome.equals("Nome")) && (cpf.isEmpty() || cpf.equals("CPF"))) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um nome ou CPF para exclusão.");
            return;
        }
        try {
            int i = JOptionPane.showConfirmDialog(null, "Deseja excluir este responsável? Essa ação é irreversível.");
            if (i == JOptionPane.YES_OPTION) {
                A.Excluir(nome, cpf);
                A.btconsultar("", ""); // Atualiza a tabela após a exclusão
                lblIDResp.setText("");
                lblCPFResp.setText("");
                lblNomeResp.setText("");
                lblEmailResp.setText("");
                lblNascResp.setText("");
                lblEnderecoResp.setText("");
                lblTelefoneResp.setText("");
                lblGeneroResp.setText("");
                txtNomeRespP.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaConsResp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDeletarRespActionPerformed

    private void btLimparRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparRespActionPerformed
        lblIDResp.setText("");
        lblCPFResp.setText("");
        lblNomeResp.setText("");
        lblEmailResp.setText("");
        lblNascResp.setText("");
        lblEnderecoResp.setText("");
        lblTelefoneResp.setText("");
        lblGeneroResp.setText("");
        txtNomeRespP.setText("");
    }//GEN-LAST:event_btLimparRespActionPerformed

    private void btLimparRespMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparRespMouseExited
        btLimparResp.setBackground(new Color(142, 202, 230));
    }//GEN-LAST:event_btLimparRespMouseExited

    private void btLimparRespMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparRespMouseEntered
        btLimparResp.setBackground(new Color(251, 133, 0));
    }//GEN-LAST:event_btLimparRespMouseEntered

    private void lblIDRespInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblIDRespInputMethodTextChanged

    }//GEN-LAST:event_lblIDRespInputMethodTextChanged

    private void lblCPFRespInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblCPFRespInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCPFRespInputMethodTextChanged

    private void btpesquisadeRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisadeRespActionPerformed
        btconsulta(txtNomeRespP.getText());
    }//GEN-LAST:event_btpesquisadeRespActionPerformed

    private void txtNomeRespPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRespPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRespPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDelResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDelResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDelResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDelResp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDelResp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeletarResp;
    private javax.swing.JButton btLimparResp;
    private javax.swing.JButton btnVoltarExcResp;
    private javax.swing.JButton btpesquisadeResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBottomC;
    private javax.swing.JLabel lblCPFResp;
    private javax.swing.JLabel lblEmailResp;
    private javax.swing.JLabel lblEnderecoResp;
    private javax.swing.JLabel lblGeneroResp;
    private javax.swing.JLabel lblIDResp;
    private javax.swing.JLabel lblNascResp;
    private javax.swing.JLabel lblNomeResp;
    private javax.swing.JLabel lblTelefoneResp;
    private javax.swing.JLabel lblTopoC;
    private javax.swing.JPanel pnlBottomC;
    private javax.swing.JPanel pnlPrincipalC;
    private javax.swing.JPanel pnlTopoC;
    private javax.swing.JTextField txtNomeRespP;
    // End of variables declaration//GEN-END:variables
}
